import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,statSync,existsSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {MEDIA_CATALOG} from '../src/media-catalog.js';import {LOCAL_MODELS} from '../src/aux-catalog.js';import {MediaDownloads} from '../src/media-downloads.js';import {Core} from '../src/core.js';import {createApp} from '../src/server.js';
test('360 novas entradas visuais, sem duplicar repositórios; todos os arquivos são fixados',()=>{
 assert.equal(MEDIA_CATALOG.length,366);assert.equal(new Set(MEDIA_CATALOG.map(m=>m.repo.toLowerCase())).size,366);assert.equal(MEDIA_CATALOG.filter(m=>m.id.startsWith('visual-')).length,360);assert.equal(MEDIA_CATALOG.filter(m=>m.id.startsWith('visual-')&&m.kind==='video').length,100);
 for(const m of MEDIA_CATALOG){assert.ok(m.description.length>30);assert.match(m.revision,/^[a-f0-9]{40}$/);assert.ok(m.files.length);if(m.id.startsWith('visual-'))assert.equal(m.access,'public');const seen=new Set();for(const f of m.files){assert.ok(!f.path.split('/').some(p=>p==='..'||p==='.'||!p));assert.match(f.path,/\.(gguf|safetensors)$/);assert.match(f.sha256,/^[a-f0-9]{64}$/);assert.ok(Number.isSafeInteger(f.bytes)&&f.bytes>0);assert.ok(!seen.has(f.path));seen.add(f.path);}if(m.local_profile&&!m.profile_id){const p=LOCAL_MODELS.find(p=>p.id===m.id)!;assert.ok(p);assert.equal(p.kind,'image');assert.equal(p.files[0].sha256,m.files[m.profile_file!].sha256);assert.ok(!p.files[0].file.includes('/'));}}
 assert.ok(LOCAL_MODELS.length>6);
});
const payload=Buffer.from('safe weights fixture with a partial download'),sha=createHash('sha256').update(payload).digest('hex');
const wait=async(fn:()=>boolean)=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout de fixture');};
test('Download visual pausa, sobrevive a reinício e retoma com hash verificado sem enviar token à CDN',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'visual-download-')),id='visual-fixture',model={...MEDIA_CATALOG[0],id,repo:'fixture/model',revision:'a'.repeat(40),files:[{path:'weights/model.safetensors',bytes:payload.length,sha256:sha}]};MEDIA_CATALOG.push(model);const old=globalThis.fetch,token='hf_'+'a'.repeat(24);let resume=false,requests=0;
 globalThis.fetch=(async(url:any,init:any)=>{const u=String(url);if(u.includes('/api/models/'))return Response.json({sha:model.revision,siblings:[{rfilename:model.files[0].path,size:payload.length,lfs:{sha256:sha}}]});if(u.startsWith('https://huggingface.co')){assert.equal(init.headers.Authorization,'Bearer '+token);return new Response(null,{status:302,headers:{location:'https://cdn.hf.co/weights'}});}assert.equal(init.headers.Authorization,undefined);requests++;if(resume){assert.equal(init.headers.Range,'bytes=8-');return new Response(payload.subarray(8),{status:206,headers:{'content-range':`bytes 8-${payload.length-1}/${payload.length}`}});}return new Response(new ReadableStream({start(c){c.enqueue(payload.subarray(0,8));init.signal.addEventListener('abort',()=>c.error(new Error('aborted')),{once:true});}}));}) as typeof fetch;
 const library=new MediaDownloads(dir,()=>token),partial=join(library.directory,id,'weights/model.safetensors.part');try{await library.download(id,0);await wait(()=>existsSync(partial)&&statSync(partial).size===8);await library.pause();assert.equal(library.snapshot().jobs[0].state,'paused');assert.equal(readFileSync(partial).length,8);resume=true;const reopened=new MediaDownloads(dir,()=>token);await reopened.download(id,0);await wait(()=>!reopened.busy);assert.equal(reopened.snapshot().jobs[0].state,'downloaded');assert.deepEqual(readFileSync(partial.slice(0,-5)),payload);assert.equal(requests,2);await assert.rejects(reopened.download(id,999));}finally{await library.pause();globalThis.fetch=old;MEDIA_CATALOG.pop();rmSync(dir,{recursive:true,force:true});}
});
test('Erro na credencial libera o slot do download visual',async()=>{const dir=mkdtempSync(join(tmpdir(),'visual-fail-')),library=new MediaDownloads(dir,()=>{throw Error('Cofre indisponível');});try{const m=MEDIA_CATALOG.find(m=>m.files[0].bytes<1e9)!;assert.ok(m);await library.download(m.id,0);await wait(()=>!library.busy);assert.equal(library.snapshot().jobs[0].state,'failed');}finally{await library.pause();rmSync(dir,{recursive:true,force:true});}});
test('Rotas visuais exigem sessão e bloqueio; ícones públicos não abrem caminhos arbitrários',async()=>{const dir=mkdtempSync(join(tmpdir(),'visual-http-')),core=new Core(dir,resolve('.'));await core.init();await core.setup('senha-fixture-segura');const {app}=await createApp(core,'visual-session'),headers={host:'127.0.0.1:4317',authorization:'Bearer visual-session'};try{assert.equal((await app.inject({method:'GET',url:'/v1/media-downloads',headers:{host:headers.host}})).statusCode,401);assert.equal((await app.inject({method:'POST',url:'/v1/media-downloads',headers,payload:{model:'../../vault',file:0}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:'/v1/media-downloads',headers,payload:{model:MEDIA_CATALOG[0].id,file:-1}})).statusCode,400);assert.equal((await app.inject({method:'GET',url:'/model-icons.js',headers:{host:headers.host}})).statusCode,200);assert.notEqual((await app.inject({method:'GET',url:'/model-icons/../../vault.enc.json',headers})).statusCode,200);await app.inject({method:'POST',url:'/v1/lock',headers,payload:{}});assert.equal((await app.inject({method:'POST',url:'/v1/media-downloads/pause',headers,payload:{}})).statusCode,423);}finally{await app.close();await core.close();rmSync(dir,{recursive:true,force:true});}});
