import test from 'node:test';import assert from 'node:assert/strict';
import{uid,newProject,addClip,splitClip,sceneAt,duration,validateProject,LIMITS}from'../public/studio-project.js';
const asset=(kind='video')=>({id:crypto.randomUUID(),name:'sample',kind,duration:12,bytes:1000,width:1280,height:720});
test('Split preserves total duration and source offsets across both cuts',()=>{const p=newProject(),a=asset();p.assets.push(a);addClip(p,a);splitClip(p,3);splitClip(p,7);assert.equal(duration(p),10);assert.deepEqual(p.clips.map(c=>[c.trim,c.duration]),[[0,3],[3,4],[7,3]]);assert.equal(sceneAt(p,3).index,1);assert.equal(sceneAt(p,9).local,2);assert.doesNotThrow(()=>validateProject(p));});
test('Timeline rejects cuts at borders and oversized projects',()=>{const p=newProject(),a=asset('image');p.assets.push(a);addClip(p,a);assert.throws(()=>splitClip(p,0));assert.throws(()=>splitClip(p,3.9));p.clips[0].duration=LIMITS.seconds;assert.throws(()=>addClip(p,a));});
test('Imported projects cannot reference missing media or trim beyond source',()=>{const p=newProject(),a=asset();p.assets.push(a);addClip(p,a);p.clips[0].trim=4;assert.throws(()=>validateProject(p));p.clips[0].trim=0;p.clips[0].asset='missing';assert.throws(()=>validateProject(p));});
test('Project validation rejects nonfinite times, excess media and duplicate IDs',()=>{const p=newProject(),a=asset('image');p.assets.push(a);addClip(p,a);p.clips[0].duration=NaN;assert.throws(()=>validateProject(p));p.clips[0].duration=4;p.assets.push({...a});assert.throws(()=>validateProject(p));p.assets.pop();p.assets[0].bytes=LIMITS.bytes+1;assert.throws(()=>validateProject(p));});
test('Text and music tracks retain independent offsets through validation',()=>{const p=newProject(),a=asset('image'),music=asset('audio');p.assets.push(a,music);addClip(p,a);p.music={asset:music.id,start:1,trim:2,volume:.5};p.texts=[{id:crypto.randomUUID(),text:'Hello',start:1,duration:2,size:5,position:'bottom',color:'#ffffff',box:true}];assert.deepEqual(validateProject(p),p);p.music.asset=a.id;assert.throws(()=>validateProject(p));});
test('Camadas e áudio extra validam mídia, intervalos e identidade',()=>{const p=newProject(),a={id:uid(),name:'imagem.png',kind:'image',duration:0,bytes:100,width:512,height:512};p.assets.push(a);addClip(p,a);p.layers.push({id:uid(),asset:a.id,start:0,duration:3,trim:0,x:.5,y:.5,width:.3,opacity:.8,volume:0});assert.equal(validateProject(p).layers.length,1);p.layers[0].width=2;assert.throws(()=>validateProject(p));p.layers[0].width=.3;p.audios.push({id:uid(),asset:a.id,start:0,trim:0,volume:1});assert.throws(()=>validateProject(p));});
