import {windowsRuntimeReady,windowsRuntimeMessage} from './platform.js';
import {spawn,type ChildProcess} from 'node:child_process';
import {existsSync,mkdirSync,readFileSync,writeFileSync,rmSync,renameSync,statSync,statfsSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {randomUUID,randomInt} from 'node:crypto';
import {availableParallelism,release} from 'node:os';
import {LOCAL_MODELS} from './aux-catalog.js';
import {downloadVerified} from './model-library.js';
import {memoryStatus} from './model.js';
export function validateWav(buffer:Buffer){
 if(buffer.length<44||buffer.length>2880044||buffer.toString('ascii',0,4)!=='RIFF'||buffer.toString('ascii',8,12)!=='WAVE'||buffer.toString('ascii',12,16)!=='fmt '||buffer.readUInt32LE(16)!==16||buffer.readUInt16LE(20)!==1||buffer.readUInt16LE(22)!==1||buffer.readUInt32LE(24)!==16000||buffer.readUInt32LE(28)!==32000||buffer.readUInt16LE(32)!==2||buffer.readUInt16LE(34)!==16||buffer.toString('ascii',36,40)!=='data'||buffer.readUInt32LE(40)!==buffer.length-44||buffer.readUInt32LE(4)!==buffer.length-8||(buffer.length-44)%2)throw new Error('Áudio inválido: envie WAV mono PCM 16 bits, 16 kHz, até 90 segundos.');
 if(buffer.length<3244)throw new Error('Grave ao menos um instante de fala.');return (buffer.length-44)/32000;
}
export function voiceInput(buffer:Buffer,language='pt'){
 const seconds=validateWav(buffer);if(!['pt','en','es','auto'].includes(language))throw new Error('Idioma de transcrição inválido.');
 let power=0,clipped=0;const count=(buffer.length-44)/2;for(let i=44;i<buffer.length;i+=2){const x=buffer.readInt16LE(i)/32768;power+=x*x;if(Math.abs(x)>.995)clipped++;}
 const rms=Math.sqrt(power/count);if(rms<0.00015)throw new Error('Não detectei áudio suficiente. Confira o microfone e tente falar um pouco mais perto.');
 const warnings=clipped/count>.01?['O áudio ficou saturado. Afaste um pouco o microfone e revise a transcrição.']:rms<.003?['O áudio está baixo. Aproxime o microfone e revise a transcrição.']:[];
 return {seconds,language,warnings};
}
type Job={id:string;model:string;state:string;progress?:number;total?:number;error?:string;file?:string;kind?:string;at:number};
export class AuxRuntime{
 private killTimer:NodeJS.Timeout|null=null;private running:Promise<void>|null=null;private process:ChildProcess|null=null;private controller:AbortController|null=null;private pending:Promise<void>|null=null;
 private manifest:any;readonly folder:string;download:Job|null=null;generation:Job|null=null;
 constructor(directory:string,root:string){this.folder=join(directory,'local-engines');mkdirSync(this.folder,{recursive:true,mode:0o700});this.manifest=existsSync(join(root,'runtime/tools-manifest.json'))?JSON.parse(readFileSync(join(root,'runtime/tools-manifest.json'),'utf8')):{engines:{}};this.root=root;}
 private root:string;
 available(engine:string){const asset=this.manifest.engines[engine]?.assets[process.platform+'-'+process.arch];return Boolean(asset&&existsSync(this.binary(engine))&&(!asset.min_darwin_kernel||process.platform!=='darwin'||Number(release().split('.')[0])>=asset.min_darwin_kernel));}
 get busy(){return Boolean(this.process)}
 binary(engine:string){const asset=this.manifest.engines[engine]?.assets[process.platform+'-'+process.arch];return asset?join(this.root,'runtime',asset.binary):'';}
 model(id:string){const model=LOCAL_MODELS.find(m=>m.id===id);if(!model)throw new Error('Modelo fora do catálogo de motores locais');return model;}
 installed(id:string){const m=this.model(id);return existsSync(join(this.folder,id,'verified.json'))&&m.files.every(f=>{try{return statSync(join(this.folder,id,f.file)).size===f.bytes}catch{return false}});}
 snapshot(){return {platform:process.platform,busy:this.busy,download:this.download,generation:this.generation,models:LOCAL_MODELS.map(m=>({...m,bytes:m.files.reduce((n,f)=>n+f.bytes,0),available:this.available(m.engine),requirement:m.engine==='diffusion'?'Mac com macOS 26 ou mais recente; Linux Ubuntu 24.04 ou compatível; Windows x64.':'Mac Apple Silicon, Windows x64 e Linux x64.',installed:this.installed(m.id),partial:existsSync(join(this.folder,m.id+'.part'))})),engines:Object.entries(this.manifest.engines).map(([name,e]:[string,any])=>({name,release:e.release,source:e.source,available:this.available(name)}))};}
 async startDownload(id:string){const m=this.model(id);if(this.installed(id))return {state:'installed'};if(this.pending)throw new Error('Aguarde o download atual deste motor.');const total=m.files.reduce((n,f)=>n+f.bytes,0),retained=m.files.reduce((n,f)=>{try{return n+Math.min(f.bytes,statSync(join(this.folder,id+'.part',f.file)).size)}catch{return n}},0),disk=statfsSync(this.folder);if(disk.bavail*disk.bsize<total-retained+1024**3)throw new Error('Espaço em disco insuficiente.');const job:Job={id:randomUUID(),model:id,state:'downloading',progress:0,total,at:Date.now()};this.download=job;const controller=new AbortController();this.controller=controller;const temp=join(this.folder,id+'.part'),target=join(this.folder,id);
 this.pending=Promise.resolve().then(async()=>{try{mkdirSync(temp,{mode:0o700,recursive:true});let completed=0;for(const file of m.files){await downloadVerified({...file,id,name:m.name} as any,join(temp,file.file),controller.signal,n=>{job.progress=completed+n;},fetch,{resume:true});completed+=file.bytes;}writeFileSync(join(temp,'verified.json'),JSON.stringify(m.files),{mode:0o600});if(existsSync(target))throw new Error('Pasta de modelo já existe. Confira os arquivos antes de tentar substituir.');renameSync(temp,target);job.state='installed';}catch(e){job.state=controller.signal.aborted?'paused':'failed';job.error=(e as Error).message;}finally{this.pending=null;this.controller=null;}});return job;}
 async cancelDownload(){this.controller?.abort();await this.pending;}
 private async run(binary:string,args:string[],timeout:number){if(!windowsRuntimeReady())throw new Error(windowsRuntimeMessage);if(this.process)throw new Error('Outro motor de áudio ou imagem está trabalhando.');if(!existsSync(binary))throw new Error('Motor não incluído neste pacote/plataforma.');const task=new Promise<void>((resolve,reject)=>{const child=spawn(binary,args,{cwd:join(this.root,'runtime'),shell:false,windowsHide:true,stdio:['ignore','ignore','pipe']});this.process=child;let error='';child.stderr?.on('data',b=>{error=(error+b.toString()).slice(-1500)});const timer=setTimeout(()=>this.stop(),timeout);const clear=()=>{clearTimeout(timer);if(this.killTimer)clearTimeout(this.killTimer);this.killTimer=null;};child.once('error',()=>{clear();this.process=null;reject(new Error('Não foi possível iniciar o motor local.'))});child.once('exit',(code,signal)=>{clear();this.process=null;if(code===0)resolve();else reject(new Error(signal?'Processamento cancelado ou tempo esgotado.':'O motor local não concluiu. Verifique a memória disponível e a compatibilidade do modelo.'));});});this.running=task;try{await task}finally{this.running=null}}
 private admit(id:string){const m=this.model(id);if(!this.available(m.engine))throw new Error('Motor indisponível nesta plataforma ou versão do sistema.');if(!this.installed(id))throw new Error('Baixe este modelo primeiro.');if(this.busy)throw new Error('Aguarde o motor atual.');if(memoryStatus().available_memory_bytes<(m.ram_gib+1)*1024**3)throw new Error('Libere memória: descarregue a IA de texto ou feche aplicativos antes de usar este motor.');return m;}
 async transcribe(id:string,buffer:Buffer,language='pt'){const {seconds,warnings}=voiceInput(buffer,language),m=this.admit(id);if(m.kind!=='speech')throw new Error('Escolha um modelo de transcrição.');const temp=join(this.folder,'audio-'+randomUUID());mkdirSync(temp,{mode:0o700});const file=join(temp,'input.wav'),out=join(temp,'text');writeFileSync(file,buffer,{mode:0o600});try{await this.run(this.binary('whisper'),['-m',join(this.folder,id,m.files[0].file),'-f',file,'-l',language,'-t',String(Math.min(6,availableParallelism())),'-bs','5','-bo','5','-sns','-otxt','-oj','-ml','48','-sow','-of',out,'-nt'],180000);const text=readFileSync(out+'.txt','utf8').trim();if(!text)throw new Error('Nenhuma fala reconhecida. Tente novamente.');const details=JSON.parse(readFileSync(out+'.json','utf8'));const segments=(details.transcription||[]).map((s:any)=>({start:s.offsets.from/1000,end:s.offsets.to/1000,text:String(s.text).trim()})).filter((s:any)=>Number.isFinite(s.start)&&Number.isFinite(s.end)&&s.end>s.start&&s.text);return {text:text.slice(0,32000),segments,seconds,language,warnings,engine:'whisper.cpp',local:true};}finally{rmSync(temp,{recursive:true,force:true});}}
 async generate(id:string,prompt:string,steps:number,options:{seed?:number;negative?:string;aspect?:string;image?:Buffer;mask?:Buffer;strength?:number}={}){const m=this.admit(id);if(m.kind==='speech')throw new Error('Este modelo é de transcrição.');const uid=randomUUID(),folder=join(this.folder,'outputs',uid);mkdirSync(folder,{recursive:true,mode:0o700});const output=join(folder,m.kind==='video'?'result.webp':'result.png');const path=(role:string)=>join(this.folder,id,m.files.find(f=>f.role===role)!.file);const seed=options.seed??randomInt(0,2147483647);const size=m.kind==='video'?[256,256]:options.aspect==='16:9'?[768,448]:options.aspect==='9:16'?[448,768]:[512,512];const args=['-p',prompt,'-o',output,'-t',String(Math.min(8,availableParallelism())),'--steps',String(steps),'--seed',String(seed),'--offload-to-cpu','--mmap','--vae-tiling','--diffusion-fa'];
 if(options.image){if(m.kind!=='image'||!options.mask)throw Error('Edição por máscara exige imagem e modelo de imagem.');for(const [name,data] of [['init.png',options.image],['mask.png',options.mask]] as const){if(data.length<33||data.length>5*1024**2||data.toString('hex',0,8)!=='89504e470d0a1a0a'||data.readUInt32BE(16)!==512||data.readUInt32BE(20)!==512)throw Error('Envie PNG de 512 × 512 e até 5 MiB.');writeFileSync(join(folder,name),data,{mode:0o600});}args.push('--init-img',join(folder,'init.png'),'--mask',join(folder,'mask.png'),'--strength',String(options.strength??.75));}
 if(options.negative)args.push('-n',options.negative);
 if(m.kind==='image')args.push('--type','f16','-m',path('model'),'-W',String(size[0]),'-H',String(size[1]));else args.push('-M','vid_gen','--diffusion-model',path('diffusion'),'--vae',path('vae'),'--t5xxl',path('t5'),'-W','256','-H','256','--video-frames','17','--cfg-scale','6','--sampling-method','euler','--flow-shift','3','--temporal-tiling','--tensor-type-rules','first_stage_model\\.=f16');
 const job:Job={id:uid,model:id,kind:m.kind,state:'running',at:Date.now()};this.generation=job;void this.run(this.binary('diffusion'),args,30*60000).then(()=>{if(!existsSync(output))throw new Error('O motor não produziu o arquivo esperado.');job.state='complete';job.file='/v1/local-engines/artifacts/'+uid;writeFileSync(join(folder,'result.json'),JSON.stringify({kind:m.kind,model:id,prompt,negative:options.negative||'',seed,width:size[0],height:size[1],steps,at:job.at}),{mode:0o600});}).catch(e=>{job.state='failed';job.error=e.message;});return job;}
 gallery(){const folder=join(this.folder,'outputs');if(!existsSync(folder))return [];return readdirSync(folder).filter(id=>/^[a-f0-9-]{36}$/.test(id)).flatMap(id=>{try{const record=JSON.parse(readFileSync(join(folder,id,'result.json'),'utf8'));const ext=record.kind==='video'?'webp':'png';if(!existsSync(join(folder,id,'result.'+ext)))return [];return [{...record,id,file:'/v1/local-engines/artifacts/'+id}];}catch{return [];}}).sort((a,b)=>b.at-a.at).slice(0,100);}
 artifact(id:string){if(!/^[a-f0-9-]{36}$/.test(id))throw new Error('Arquivo inválido.');const folder=join(this.folder,'outputs',id);const record=JSON.parse(readFileSync(join(folder,'result.json'),'utf8'));const file=join(folder,record.kind==='video'?'result.webp':'result.png');return {file,type:record.kind==='video'?'image/webp':'image/png'};}
 stop(){const child=this.process;if(!child)return;child.kill('SIGTERM');if(!this.killTimer)this.killTimer=setTimeout(()=>{if(this.process===child)child.kill('SIGKILL');},3000);}
 async close(){await this.cancelDownload();this.stop();await this.running?.catch(()=>{});}
}
