import type {OAuthClientProvider} from '@modelcontextprotocol/sdk/client/auth.js';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {z} from 'zod';
import {randomBytes,randomUUID,createHash,createCipheriv,createDecipheriv} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync,renameSync} from 'node:fs';
import {join,isAbsolute} from 'node:path';
import type {Vault} from './vault.js';
import type {ToolDefinition} from './inference.js';
export const connectionSchema=z.strictObject({name:z.string().trim().min(1).max(80),url:z.string().max(2048).default(''),token:z.string().max(4096).default(''),oauth:z.boolean().default(false),client_id:z.string().max(256).default(''),command:z.string().max(2048).default(''),args:z.array(z.string().max(2048)).max(30).default([])}).refine(v=>Boolean(v.url)!==Boolean(v.command),'Escolha URL ou comando local.');
type Config=z.infer<typeof connectionSchema>&{id:string;auth?:{client?:any;tokens?:any;verifier?:string}};
type Live={client:Client;tools:any[];connected:boolean;error?:string};
export class Connections{
 private file:string;private live=new Map<string,Live>();private generation=0;private authorizations=new Map<string,{id:string;expires:number;url?:string;transport?:StreamableHTTPClientTransport}>();
 constructor(directory:string,private vault:Vault,private origin='http://127.0.0.1:4317'){this.file=join(directory,'connections.enc.json');}
 private key(){return createHash('sha256').update(this.vault.key('service')).update('localneuron-mcp-v1').digest();}
 private read():Config[]{const key=this.key();if(!existsSync(this.file))return [];const v=JSON.parse(readFileSync(this.file,'utf8')),d=createDecipheriv('aes-256-gcm',key,Buffer.from(v.iv,'hex'));d.setAuthTag(Buffer.from(v.tag,'hex'));return z.array(connectionSchema.and(z.object({id:z.string().uuid(),auth:z.object({client:z.record(z.string(),z.unknown()).optional(),tokens:z.record(z.string(),z.unknown()).optional(),verifier:z.string().optional()}).optional()}))).max(30).parse(JSON.parse(Buffer.concat([d.update(Buffer.from(v.data,'base64')),d.final()]).toString()));}
 private save(value:Config[]){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',this.key(),iv),data=Buffer.concat([c.update(JSON.stringify(value)),c.final()]);writeFileSync(this.file+'.tmp',JSON.stringify({iv:iv.toString('hex'),tag:c.getAuthTag().toString('hex'),data:data.toString('base64')}),{mode:0o600});renameSync(this.file+'.tmp',this.file);}
 list(){return this.read().map(({token,command,args,auth,...row})=>({...row,authorization_url:[...this.authorizations.values()].find(a=>a.id===row.id&&a.expires>Date.now())?.url,local:Boolean(command),connected:this.live.get(row.id)?.connected??false,error:this.live.get(row.id)?.error,tools:(this.live.get(row.id)?.tools??[]).map(t=>({name:t.name,description:t.description}))}));}
 async add(input:unknown){const v=connectionSchema.parse(input);if(v.command&&!isAbsolute(v.command))throw Error('Use o caminho absoluto do executável local.');if(v.url){const u=new URL(v.url);if(u.username||u.password||u.hash||!(u.protocol==='https:'||u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error('Use HTTPS ou HTTP no próprio computador. Não inclua credenciais na URL.');}
 const configs=this.read();if(configs.length>=30)throw Error('Limite de 30 conexões.');if(configs.some(c=>c.url===v.url&&c.command===v.command&&JSON.stringify(c.args)===JSON.stringify(v.args)))throw Error('Este servidor já foi adicionado. Use reconectar.');const value={...v,id:randomUUID()};this.save([...configs,value]);await this.test(value.id);return this.list().find(c=>c.id===value.id);}
 private updateAuth(id:string,patch:any){const configs=this.read(),config=configs.find(c=>c.id===id);if(!config)throw Error('Conexão revogada.');config.auth={...config.auth,...patch};this.save(configs);}
 private provider(config:Config,state:string):OAuthClientProvider{return {redirectUrl:this.origin+'/v1/connections/oauth/callback',clientMetadata:{client_name:'LocalNeuron',redirect_uris:[this.origin+'/v1/connections/oauth/callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none'},state:()=>state,clientInformation:()=>this.read().find(c=>c.id===config.id)?.auth?.client||(config.client_id?{client_id:config.client_id}:undefined),saveClientInformation:v=>this.updateAuth(config.id,{client:v}),tokens:()=>this.read().find(c=>c.id===config.id)?.auth?.tokens,saveTokens:v=>this.updateAuth(config.id,{tokens:v}),saveCodeVerifier:v=>this.updateAuth(config.id,{verifier:v}),codeVerifier:()=>{const value=this.read().find(c=>c.id===config.id)?.auth?.verifier;if(!value)throw Error('Autorização expirada.');return value;},redirectToAuthorization:url=>{if(url.protocol!=='https:'&&url.origin!==new URL(config.url).origin)throw Error('Use um provedor OAuth HTTPS.');const flow=this.authorizations.get(state);if(!flow)throw Error('Autorização expirada.');flow.url=url.href;},invalidateCredentials:scope=>{if(scope==='tokens')this.updateAuth(config.id,{tokens:undefined});else if(scope==='verifier')this.updateAuth(config.id,{verifier:undefined});else this.updateAuth(config.id,{client:undefined,tokens:undefined,verifier:undefined});}};}
 async callback(state:string,code:string){const flow=this.authorizations.get(state);if(!flow||flow.expires<Date.now()||!flow.transport)throw Error('Autorização ausente ou expirada. Volte ao LocalNeuron e tente novamente.');this.authorizations.delete(state);this.key();await flow.transport.finishAuth(code);return this.test(flow.id);}
 async test(id:string){const config=this.read().find(c=>c.id===id);if(!config)throw Error('Conexão não encontrada.');const generation=this.generation;await this.live.get(id)?.client.close().catch(()=>{});const client=new Client({name:'LocalNeuron',version:'0.25.0'},{capabilities:{}}),live:Live={client,tools:[],connected:false};this.live.set(id,live);
 try{const state=randomBytes(32).toString('base64url');for(const [key,flow]of this.authorizations)if(flow.id===id||flow.expires<Date.now())this.authorizations.delete(key);if(config.oauth)this.authorizations.set(state,{id,expires:Date.now()+600000});const transport=config.command?new StdioClientTransport({command:config.command,args:config.args,stderr:'ignore',env:{PATH:process.env.PATH??'',...(process.env.HOME?{HOME:process.env.HOME}:{})}}):new StreamableHTTPClientTransport(new URL(config.url),{...(config.oauth?{authProvider:this.provider(config,state)}:{}),requestInit:{headers:config.token?{Authorization:'Bearer '+config.token}:{},redirect:'error'},fetch:async(url,init)=>{const target=new URL(typeof url==='string'?url:url.href);if(target.origin!==new URL(config.url).origin&&(!config.oauth||target.protocol!=='https:'))throw Error('Origem MCP recusada.');return fetch(url,{...init,redirect:'error',signal:init?.signal?AbortSignal.any([init.signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000)});}});
 if(config.oauth)this.authorizations.get(state)!.transport=transport as StreamableHTTPClientTransport;await client.connect(transport,{timeout:20000});const result=await client.listTools({}, {timeout:15000});if(result.tools.length>64||JSON.stringify(result.tools).length>131072)throw Error('Servidor excede o limite de 64 ferramentas / 128 KiB de definições.');if(generation!==this.generation||this.vault.locked||this.live.get(id)!==live)throw Error('Conexão cancelada.');live.tools=result.tools;live.connected=true;client.onclose=()=>{live.connected=false;};client.onerror=()=>{live.error='A comunicação MCP falhou. Teste a conexão novamente.';};
 }catch(e){await client.close().catch(()=>{});live.connected=false;live.error=(e as Error).message.replace(/Bearer\s+\S+/gi,'Bearer [oculto]').slice(0,300);}
 return this.list().find(c=>c.id===id);}
 async remove(id:string){this.generation++;for(const [key,flow]of this.authorizations)if(flow.id===id)this.authorizations.delete(key);const configs=this.read();this.save(configs.filter(c=>c.id!==id));await this.live.get(id)?.client.close().catch(()=>{});this.live.delete(id);return {ok:true};}
 definitions(ids:string[],readOnly:boolean):ToolDefinition[]{if(this.vault.locked)return [];return ids.flatMap(id=>{const live=this.live.get(id);if(!live?.connected)return [];return live.tools.filter(t=>!readOnly||t.annotations?.readOnlyHint===true).map((t,i)=>({type:'function' as const,function:{name:'mcp_'+id.replaceAll('-','')+'_'+i,description:(t.name+': '+(t.description??'Ferramenta MCP')).slice(0,1000),parameters:t.inputSchema}}));}).slice(0,32);}
 async call(name:string,args:unknown,ids:string[],signal:AbortSignal){this.key();const match=/^mcp_([a-f0-9]{32})_(\d+)$/.exec(name);const id=ids.find(id=>id.replaceAll('-','')===match?.[1]),live=id?this.live.get(id):undefined,tool=live?.tools[Number(match?.[2])];if(!id||!live?.connected||!tool)throw Error('Conexão revogada ou ferramenta não autorizada.');const result=await live.client.callTool({name:tool.name,arguments:args as Record<string,unknown>},undefined,{signal,timeout:60000});signal.throwIfAborted();if(this.vault.locked||this.live.get(id)!==live||!live.connected)throw Error('Conexão revogada.');return result;}
 async close(){this.generation++;this.authorizations.clear();await Promise.allSettled([...this.live.values()].map(c=>c.client.close()));this.live.clear();}
}
