import {PLAYBOOK_VERSION,playbook,agentMethod} from './bot-playbooks.js';
import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import type { Core } from './core.js';
import { accessSchema } from './agent-tools.js';
export const botSchema=z.strictObject({id:z.string().uuid().optional(),template:z.string().max(60).optional(),name:z.string().trim().min(1).max(80),area:z.enum(['personal','work']),role:z.string().max(120),instructions:z.string().max(6000).default(''),memory:z.string().max(6000).default(''),model:z.string().max(512).default(''),access:accessSchema.default({enabled:true,web:false,computer:true,files:false,terminal:false,readOnly:true,format:'native'}),connections:z.array(z.string().uuid()).max(20).default([]),playbook_version:z.number().int().min(1).max(1000).optional(),tasks:z.array(z.string().max(1000)).max(6).default([])});
export type Bot=z.infer<typeof botSchema>&{id:string};
export const profileSchema=z.strictObject({name:z.string().trim().max(80).default(''),use:z.enum(['personal','work','both']).default('personal'),objectives:z.string().max(2000).default(''),selected_model:z.string().max(512).default(''),step:z.number().int().min(0).max(4).default(0),completed:z.boolean().default(false)});
export type ExperienceState={personality?:boolean;profile:z.infer<typeof profileSchema>;bots:Bot[];benchmarks?:{model:string;at:number;elapsed_ms:number;tokens:number;tokens_per_second:number|null}[]};
const personal=[['assistant','Assistente pessoal','Organização'],['coach','Coach','Objetivos e hábitos'],['health','Saúde','Informações de saúde'],['finance','Finanças pessoais','Planejamento pessoal']];
const work=[['ceo','Coordenador','Estratégia'],['finance','Financeiro','Finanças da empresa'],['accounting','Contabilidade','Organização contábil'],['legal','Jurídico','Pesquisa jurídica'],['marketing','Marketing','Comunicação'],['sales','Vendas','Relacionamento comercial']];
export function legacyInstructions(name:string,role:string,kind:string){return `Você é ${name}. Ajude com ${role.toLowerCase()}. Faça perguntas quando faltar contexto, explique suas fontes e incertezas. Não invente acesso a dados ou execução de ações.${['health','legal','accounting','finance'].includes(kind)?' Ofereça informações educativas; decisões médicas, jurídicas e financeiras importantes precisam de revisão profissional.':''}`;}
export function botTemplates(use:'personal'|'work'|'both'){return [...(use!=='work'?personal.map(x=>({x,area:'personal' as const})):[]),...(use!=='personal'?work.map(x=>({x,area:'work' as const})):[])].map(({x,area})=>{const template=area+'-'+x[0];return botSchema.parse({template,name:x[1],area,role:x[2],instructions:`Você é ${x[1]}. Sua especialidade é ${x[2].toLowerCase()}.`+agentMethod(template),tasks:playbook(template)?.tasks||[],playbook_version:PLAYBOOK_VERSION});});}
export function normalizedProfile(value:unknown){const p=profileSchema.parse(value||{});return {...p,completed:p.completed||p.step===4};}
export class Experience {
 constructor(private core:Core){}
 async personality(input:unknown,key:string){const value=z.strictObject({enabled:z.boolean()}).parse(input);return this.core.idempotent(key,{operation:'experience.personality',...value},(state,entries)=>{this.state(state).personality=value.enabled;this.core.append(state,entries,'experience.personality',value);return value;});}
 async snapshot(){const state=await this.core.snapshot();const exp=state.experience??{profile:profileSchema.parse({}),bots:[],benchmarks:[]};return {...exp,profile:normalizedProfile(exp.profile)};}
 private state(state:import('./types.js').State){return state.experience??={profile:profileSchema.parse({}),bots:[],benchmarks:[]};}
 async profile(input:unknown,key:string){const parsed=profileSchema.partial().parse(input);const patch=Object.fromEntries(Object.entries(parsed).filter(([key])=>Object.hasOwn(input as object,key))) as Partial<z.infer<typeof profileSchema>>;return this.core.idempotent(key,{operation:'experience.profile',patch},(state,entries)=>{const exp=this.state(state),previous=normalizedProfile(exp.profile);const profile=normalizedProfile({...previous,...patch,completed:previous.completed||patch.completed===true});exp.profile=profile;this.core.append(state,entries,'experience.profile',{step:profile.step,completed:profile.completed});return profile;});}
 async upgrade(key:string){return this.core.idempotent(key,{operation:'experience.playbooks',version:PLAYBOOK_VERSION},(state,entries)=>{let updated=0,preserved=0;const templates=botTemplates('both');for(const bot of this.state(state).bots){const current=templates.find(t=>t.template===bot.template);if(!current||bot.playbook_version===PLAYBOOK_VERSION)continue;const kind=bot.template!.split('-')[1];if(bot.instructions===legacyInstructions(current.name,current.role,kind)){bot.instructions=current.instructions;bot.tasks=current.tasks;bot.playbook_version=PLAYBOOK_VERSION;updated++;}else preserved++;}this.core.append(state,entries,'experience.playbooks',{updated,preserved});return {updated,preserved,version:PLAYBOOK_VERSION};});}
 async suggest(input:unknown,key:string){const v=z.strictObject({use:z.enum(['personal','work','both']),model:z.string().max(512).default(''),templates:z.array(z.string().max(60)).max(10).optional()}).parse(input);return this.core.idempotent(key,{operation:'experience.team',...v},(state,entries)=>{const team=this.state(state).bots;for(const template of botTemplates(v.use)){if(v.templates&&!v.templates.includes(template.template!))continue;const existing=team.find(b=>b.template===template.template);if(!existing){if(team.length>=100)throw Error('Limite de 100 bots.');team.push({...template,id:randomUUID(),model:v.model});}else if(!existing.model&&v.model)existing.model=v.model;}this.core.append(state,entries,'experience.team',{count:team.length});return team;});}
 async bot(input:unknown,key:string){const value=botSchema.parse(input);return this.core.idempotent(key,{operation:'experience.bot',...value},(state,entries)=>{const team=this.state(state).bots,index=team.findIndex(b=>b.id===value.id);if(value.id&&index<0)throw Error('Bot não encontrado.');if(index<0&&team.length>=100)throw Error('Limite de 100 bots.');const bot={...value,id:value.id??randomUUID()};if(index<0)team.push(bot);else team[index]=bot;this.core.append(state,entries,'experience.bot',{id:bot.id});return bot;});}
 async remove(id:string){await this.core.store.tx((state,entries)=>{if(!state||this.core.vault.locked)throw Error('Cofre bloqueado');if(state.chats?.some(c=>c.bot_id===id&&c.messages.some(m=>m.status==='pending')))throw Error('Pare a resposta deste bot primeiro.');const exp=this.state(state);exp.bots=exp.bots.filter(b=>b.id!==id);for(const c of state.chats??[])if(c.bot_id===id)delete c.bot_id;this.core.append(state,entries,'experience.bot.removed',{id});});return {ok:true};}
}
