import {z} from 'zod';
import {createHash} from 'node:crypto';
import type {CatalogModel} from './catalog.js';
import {hfHeaders,hfError} from './hf-access.js';
import {LLAMA_ARCHITECTURES} from './engine-architectures.js';
export const HF_BRANDS=['Qwen','google','meta-llama','mistralai','microsoft','deepseek-ai','openai','nvidia','ibm-granite','allenai','NousResearch','MiniMaxAI','moonshotai','zai-org','BAAI','stabilityai','black-forest-labs','Wan-AI','THUDM','mlx-community','CohereLabs','HuggingFaceTB','tiiuae','ByteDance-Seed','tencent','LGAI-EXAONE','stepfun-ai','01-ai','XiaomiMiMo','arcee-ai','inclusionAI','baidu','perplexity-ai','LiquidAI','apple','Salesforce','jinaai','sentence-transformers','intfloat','Alibaba-NLP','QwenLM','rednote-hilab','Zyphra','mosaicml','PleIAs','OpenGVLab','facebook','unum-cloud','unsloth','bartowski','lmstudio-community'];
const repoSchema=z.string().regex(/^[A-Za-z0-9][\w.-]*\/[A-Za-z0-9][\w.-]*$/).max(180);
export async function hfJSON(path:string,token?:string){
 const url='https://huggingface.co/api/models'+path;const response=await fetch(url,{signal:AbortSignal.timeout(20000),redirect:'error',headers:hfHeaders(url,token)});
 if(!response.ok)throw Error(hfError(response.status));let size=0;const chunks:Uint8Array[]=[];if(!response.body)throw Error('Resposta vazia do Hugging Face');
 for await(const chunk of response.body as any as AsyncIterable<Uint8Array>){size+=chunk.length;if(size>12*1024*1024)throw Error('Metadados muito grandes. Refine a pesquisa.');chunks.push(chunk);}
 return {data:JSON.parse(Buffer.concat(chunks).toString()),next:response.headers.get('link')?.match(/<([^>]+)>; rel="next"/)?.[1]};
}
export function purpose(m:any){const type=m.pipeline_tag||m.cardData?.pipeline_tag||(textModel(m)?'text-generation':''),name=String(m.id||'').toLowerCase();if(['feature-extraction','sentence-similarity'].includes(type)||/embed(?:ding)?/.test(name))return ['Busca semântica','Transforma textos em vetores para buscar informações e comparar significados; não é um chat.'];if(/reranker/.test(name))return ['Ordenar resultados','Classifica resultados de busca conforme a relevância para a pergunta; não é um chat.'];if(type==='text-classification')return ['Análise de texto','Classifica textos por assunto, sentimento ou outras categorias declaradas na ficha.'];if(type==='image-to-image')return ['Edição de imagem','Transforma ou restaura uma imagem de entrada.'];if(type==='object-detection')return ['Visão','Localiza objetos em imagens.'];if(type==='fill-mask')return ['Preenchimento de texto','Prevê trechos ausentes em textos; não é um assistente de conversa.'];if(type==='audio-to-audio')return ['Áudio','Transforma áudio de entrada; confira se o modelo separa, melhora ou converte voz.'];if(type==='text-to-image')return ['Imagem','Gera imagens a partir de descrições.'];if(type.includes('video'))return ['Vídeo','Gera ou transforma vídeo; verifique as entradas exigidas na ficha.'];if(type==='automatic-speech-recognition')return ['Transcrição','Transforma gravações de voz em texto.'];if(type==='text-to-speech')return ['Voz','Gera fala a partir de texto.'];if(type==='image-text-to-text')return ['Visão e conversa','Interpreta imagem e texto. A entrada visual precisa de um motor compatível.'];if(/coder|code|devstral/.test(name))return ['Código','Voltado a programação, explicações e geração de código.'];if(/reason|thinking|deepseek-r1|qwq/.test(name))return ['Raciocínio','Voltado à resolução de problemas em etapas.'];if(type==='text-generation')return ['Conversa e escrita','Gera texto; variantes Instruct/Chat são adequadas para conversar.'];return ['Especializado','Modelo de '+(type||'tarefa não declarada')+'. Confira a ficha para o uso previsto.'];}

export async function searchHF(author:string,query:string,cursor?:string,token?:string){
 if(author&&!HF_BRANDS.includes(author))throw Error('Escolha uma marca da lista.');
 const params=new URLSearchParams({limit:'30',sort:'downloads',direction:'-1',full:'true',cardData:'true'});if(author)params.set('author',author);if(query)params.set('search',query.slice(0,120));if(cursor)params.set('cursor',cursor.slice(0,2000));
 const {data,next}=await hfJSON('?'+params,token);if(!Array.isArray(data))throw Error('Lista de modelos inválida.');
 return {brands:HF_BRANDS,models:data.filter((m:any)=>!m.private).map((m:any)=>{const [category,description]=purpose(m);return {repo:m.id,name:m.id.split('/').pop(),category,description,license:m.cardData?.license||'Consulte a ficha',gated:Boolean(m.gated),downloads:m.downloads,source:'https://huggingface.co/'+m.id};}),next:next?new URL(next).searchParams.get('cursor'):null};
}
export function textModel(m:any){const task=m.pipeline_tag||m.cardData?.pipeline_tag,arch=m.gguf?.architecture||'';if(/(?:^|[-_/])(embed(?:ding)?s?|reranker)(?:[-_/]|$)/i.test(String(m.id||'')))return false;return task?['text-generation','image-text-to-text'].includes(task)||task==='any-to-any'&&LLAMA_ARCHITECTURES.has(arch):typeof m.gguf?.chat_template==='string'&&m.gguf.chat_template.length>0&&!/diffusion|wan|flux|clip|t5|bert|whisper/i.test(arch);}
export function compatibility(m:any){const architecture=m.gguf?.architecture;return {engine:'llama.cpp',architecture:typeof architecture==='string'?architecture:null,state:!textModel(m)?'unsupported':!architecture?'unknown':LLAMA_ARCHITECTURES.has(architecture)?'declared':'unsupported',note:!textModel(m)?'Este motor do chat recebe modelos de texto. Use os perfis compatíveis do Estúdio para mídia.':!architecture?'Arquitetura não declarada na fonte; execução ainda precisa de validação.':LLAMA_ARCHITECTURES.has(architecture)?'Arquitetura declarada pelo motor integrado. Isso não equivale a um teste deste modelo e desta quantização.':'A arquitetura ainda não é declarada pelo motor integrado desta versão.'};}
export function ggufVariants(m:any){
 const groups=new Map<string,{id:string;quantization:string;name:string;files:any[];bytes:number;ram_gib:number}>();
 for(const file of m.siblings||[]){const path=String(file.rfilename||'');if(/mmproj|imatrix|(?:^|[-_/])(?:mtp|draft|projector|dspark)(?:[-_.\/]|$)/i.test(path))continue;
  const found=/(?:^|[-_])((?:UD-)?(?:I?Q\d[A-Z0-9_]*|TQ\d[A-Z0-9_]*)|BF16|F16|F32|MXFP4|NVFP4)(?:-\d{5}-of-\d{5})?\.gguf$/i.exec(path);if(!found)continue;
  const group=path.replace(/-\d{5}-of-\d{5}(?=\.gguf$)/i,'');let value=groups.get(group);if(!value){value={id:createHash('sha256').update(group).digest('hex').slice(0,20),quantization:found[1].toUpperCase(),name:group.split('/').at(-1)!,files:[],bytes:0,ram_gib:0};groups.set(group,value);}value.files.push(file);
 }
 const result=[];
 for(const v of groups.values()){
  v.files.sort((a,b)=>a.rfilename.localeCompare(b.rfilename));const split=/^(.*)-(\d{5})-of-(\d{5})\.gguf$/i.exec(v.files[0].rfilename);
  if(split&&(Number(split[3])!==v.files.length||v.files.some((f:any,i:number)=>f.rfilename!==`${split[1]}-${String(i+1).padStart(5,'0')}-of-${split[3]}.gguf`)))continue;
  if(!split&&v.files.length!==1)continue;
  if(v.files.some(f=>!/^([\w.-]+\/)*[\w.-]+\.gguf$/i.test(f.rfilename)||f.rfilename.split('/').some((p:string)=>p==='..'||p==='.')||!Number.isSafeInteger(f.size)||f.size<=0||!(/^[a-f0-9]{64}$/.test(f.lfs?.sha256))))continue;
  v.bytes=v.files.reduce((n,f)=>n+f.size,0);if(!Number.isSafeInteger(v.bytes))continue;v.ram_gib=Math.ceil(v.bytes/1024**3*1.25+1);result.push(v);
 }
 const preferred=['Q4_K_M','UD-Q4_K_XL','Q4_0','Q5_K_M','Q8_0'];return result.sort((a,b)=>{const pa=preferred.indexOf(a.quantization),pb=preferred.indexOf(b.quantization);return (pa<0?100:pa)-(pb<0?100:pb)||a.bytes-b.bytes;});
}
export async function hfVersions(repo:string,token?:string){
 repoSchema.parse(repo);const {data:m}=await hfJSON('/'+repo+'?blobs=true',token);const variants=ggufVariants(m),support=compatibility(m);
 if(variants.length&&textModel(m))return {models:[{repo,name:repo.split('/')[1]}],note:support.note,gated:Boolean(m.gated),support,variants:variants.map(({files,...v})=>({...v,parts:files.length})),revision:m.sha};
 if(!textModel(m))return {models:[],variants:[],gated:Boolean(m.gated),support,note:'Este repositório não é executado pelo chat. A central de motores mostra quais perfis de imagem, vídeo, áudio e busca estão integrados.'};
 const query=new URLSearchParams({search:repo.split('/')[1],filter:'gguf',limit:'100',full:'true',cardData:'true',sort:'downloads',direction:'-1'});const {data}=await hfJSON('?'+query,token);
 const models=data.filter((c:any)=>{const base=c.cardData?.base_model;return !c.private&&(base===repo||Array.isArray(base)&&base.includes(repo));}).slice(0,30).map((m:any)=>({repo:m.id,name:m.id,gated:Boolean(m.gated)}));
 return {models,variants:[],gated:Boolean(m.gated),support,note:models.length?'Conversões GGUF que declaram este modelo como base. Confira o publicador, a licença e a variante.':'Nenhuma conversão correspondente encontrada. Você pode procurar por nome no Hub ou adicionar uma pasta MLX já baixada no Mac.'};
}
export async function prepareHF(repo:string,variant?:string,token?:string):Promise<CatalogModel>{repoSchema.parse(repo);const {data}=await hfJSON('/'+repo+'?blobs=true',token);return prepareHFMetadata(repo,data,{variant,allowGated:Boolean(token)});}
export function prepareHFMetadata(repo:string,m:any,options:{variant?:string;allowGated?:boolean}={}):CatalogModel{
 repoSchema.parse(repo);if(!textModel(m))throw Error('Este repositório não declara um modelo de conversa compatível. Use o Estúdio para os motores de mídia.');
 if(m.private||m.gated&&!options.allowGated)throw Error('Este modelo exige acesso ou aceite de licença na fonte. Conecte uma conta autorizada do Hugging Face.');
 if(!/^[a-f0-9]{40}$/.test(m.sha))throw Error('Versão inválida.');
 const variants=ggufVariants(m);if(!variants.length)throw Error('Não há um conjunto GGUF de texto completo, com hashes e tamanhos publicados.');
 const selected=options.variant?variants.find(v=>v.id===options.variant):variants[0];if(!selected)throw Error('A variante mudou ou não está disponível. Atualize as opções.');
 if(!options.variant&&variants.filter(v=>v.quantization===selected.quantization).length>1)throw Error('Há variantes múltiplas. Escolha o arquivo desejado.');
 const parts=selected.files.map(f=>({file:f.rfilename.split('/').at(-1),path:f.rfilename,bytes:f.size,sha256:f.lfs.sha256}));
 const [category,description]=purpose(m),base=m.cardData?.base_model,ram=selected.ram_gib;
 return {id:'hub-'+createHash('sha256').update(repo+m.sha+selected.id).digest('hex').slice(0,20),name:repo.split('/')[1].replace(/-GGUF$/i,'')+' · '+selected.quantization,author:repo.split('/')[0],family:typeof base==='string'?base.split('/')[0]:repo.split('/')[0],tag:category,categories:category==='Código'?['Código','Conversa']:category==='Raciocínio'?['Raciocínio','Conversa']:['Conversa','Escrita'],description,limitation:compatibility(m).note+' Entrada de texto; projetores de visão não são instalados. RAM estimada para contexto curto.',repo,revision:m.sha,file:parts[0].file,bytes:selected.bytes,sha256:parts[0].sha256,parts,quantization:selected.quantization,ram_gib:ram,computer_ram_gib:Math.ceil((ram+4)/8)*8,license:typeof m.cardData?.license==='string'?m.cardData.license:'Consulte a ficha',publisher:repo.split('/')[0],...(typeof m.gguf?.architecture==='string'?{architecture:m.gguf.architecture}:{}),...(typeof base==='string'&&repoSchema.safeParse(base).success?{base_model:base}:{}),...(m.gated?{requires_auth:true}:{}),...(Number.isSafeInteger(m.gguf?.total)?{parameters_b:m.gguf.total/1e9}:{}),...(Number.isSafeInteger(m.gguf?.context_length)&&m.gguf.context_length>=2048?{context_limit:m.gguf.context_length}:{})};
}
export function validSavedModel(m:any):m is CatalogModel{try{if(m.architecture!==undefined&&(typeof m.architecture!=='string'||m.architecture.length>100)||m.requires_auth!==undefined&&typeof m.requires_auth!=='boolean')return false;const strings=['name','author','family','tag','description','limitation','quantization','license','publisher'];if(!/^hub-[a-f0-9]{20}$/.test(m.id)||!repoSchema.safeParse(m.repo).success||!(/^[a-f0-9]{40}$/.test(m.revision))||strings.some(k=>typeof m[k]!=='string'||m[k].length>16000)||!Array.isArray(m.parts)||!m.parts.length||m.parts.length>999)return false;const seen=new Set();for(const p of m.parts){if(!/^[\w.-]+\.gguf$/i.test(p.file)||!/^([\w.-]+\/)*[\w.-]+\.gguf$/i.test(p.path)||p.path.split('/').some((x:string)=>x==='..'||x==='.')||p.path.split('/').at(-1)!==p.file||!(/^[a-f0-9]{64}$/.test(p.sha256))||!Number.isSafeInteger(p.bytes)||p.bytes<=0||seen.has(p.file))return false;seen.add(p.file);}return m.file===m.parts[0].file&&m.sha256===m.parts[0].sha256&&Number.isSafeInteger(m.bytes)&&m.bytes===m.parts.reduce((n:number,p:any)=>n+p.bytes,0)&&Number.isFinite(m.ram_gib)&&m.ram_gib>0&&Number.isFinite(m.computer_ram_gib)&&m.computer_ram_gib>0&&(!m.context_limit||Number.isSafeInteger(m.context_limit)&&m.context_limit>=2048)&&(!m.categories||Array.isArray(m.categories)&&m.categories.every((c:any)=>typeof c==='string'));}catch{return false;}}
