import {spawn,execFile,type ChildProcess} from 'node:child_process';
import {existsSync,mkdirSync,readFileSync,writeFileSync,readdirSync,renameSync,statSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {homedir,tmpdir} from 'node:os';
import {randomBytes,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {setTimeout as delay} from 'node:timers/promises';
export const ACE_REVISION='ca1e85fe9430179831e6bc6be790c332190a3866';
export function musicEndpoint(value:string){const u=new URL(value);if(u.protocol!=='http:'||!['127.0.0.1','[::1]','localhost'].includes(u.hostname)||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('Use uma API ACE-Step neste computador: http://127.0.0.1:8001');return u.origin;}
export const musicRequest=z.strictObject({prompt:z.string().trim().min(1).max(4000),lyrics:z.string().max(8000).default(''),instrumental:z.boolean().default(true),duration:z.number().int().min(10).max(120).default(30),bpm:z.number().int().min(30).max(300).default(120),model:z.string().min(1).max(100),language:z.enum(['pt','en','es','ja','zh','fr','de']).default('pt'),seed:z.number().int().min(0).max(2147483646).optional()});
type Job={id:string;state:'running'|'complete'|'error';prompt:string;model:string;at:number;task?:string;file?:string;error?:string};
export class Music {
 readonly home:string;readonly galleryDirectory:string;
 private child:ChildProcess|null=null;private installing=false;private key='';private endpoint='http://127.0.0.1:8001';private phase='idle';private diagnostic='';private error='';private controller:AbortController|null=null;private pending:Promise<void>|null=null;
 job:Job|null=null;
 constructor(directory:string,private root:string){directory=resolve(directory);this.root=resolve(root);this.home=join(directory,'local-engines','ace-step-1.5');this.galleryDirectory=join(directory,'music');mkdirSync(this.galleryDirectory,{recursive:true,mode:0o700});const f=join(this.home,'connection.json');if(existsSync(f)){try{this.endpoint=musicEndpoint(JSON.parse(readFileSync(f,'utf8')).endpoint);}catch{}}const j=join(this.galleryDirectory,'active.json');if(existsSync(j))try{this.job=JSON.parse(readFileSync(j,'utf8'));if(this.job?.state==='running'){this.job.state='error';this.job.error='A sessão foi encerrada. Verifique o motor antes de gerar novamente.';this.save();}}catch{}}
 get busy(){return !!this.controller||this.installing;}
 get installed(){try{const v=JSON.parse(readFileSync(join(this.home,'installed.json'),'utf8'));return v.revision===ACE_REVISION&&v.verified===true;}catch{return false;}}
 get running(){return !!this.child&&!this.installing;}
 status(){return {installed:this.installed,running:this.running,busy:this.busy,phase:this.phase,error:this.error,diagnostic:this.diagnostic.slice(-1800),endpoint:this.endpoint,job:this.job,engine:'ACE-Step 1.5',revision:ACE_REVISION};}
 private env():NodeJS.ProcessEnv{return {HOME:homedir(),USERPROFILE:homedir(),TMPDIR:tmpdir(),TEMP:tmpdir(),PATH:process.env.PATH,SYSTEMROOT:process.env.SYSTEMROOT,PROGRAMDATA:process.env.PROGRAMDATA,PROGRAMFILES:process.env.PROGRAMFILES,LANG:'en_US.UTF-8',HF_HOME:join(this.home,'cache/huggingface'),HF_HUB_CACHE:join(this.home,'cache/huggingface/hub'),HF_XET_CACHE:join(this.home,'cache/xet'),XDG_CACHE_HOME:join(this.home,'cache'),MODELSCOPE_CACHE:join(this.home,'cache/modelscope')};}
 private python(){const bundled=join(this.root,'runtime/mlx-darwin-arm64/python/bin/python3');return existsSync(bundled)?bundled:process.platform==='win32'?'python':'python3';}
 private launch(command:string,args:string[],env:NodeJS.ProcessEnv,cwd:string){
  const c=spawn(command,args,{cwd,env,detached:process.platform!=='win32',windowsHide:true,stdio:['ignore','pipe','pipe']});this.child=c;
  const log=(b:Buffer)=>{this.diagnostic=(this.diagnostic+b.toString()).slice(-6000);};c.stdout?.on('data',log);c.stderr?.on('data',log);
  c.on('error',e=>{this.error=e.message;this.phase='error';});c.on('close',code=>{if(this.child===c){this.child=null;this.installing=false;if(code){this.error=this.error||'O motor encerrou. Confira o diagnóstico.';this.phase='error';}else this.phase=this.installed?'installed':'idle';}});return c;
 }
 install(){if(this.child||this.busy)throw Error('Pare o motor antes de instalar.');if(this.installed)return this.status();mkdirSync(this.home,{recursive:true,mode:0o700});this.installing=true;this.phase='installing';this.error='';this.diagnostic='';this.launch(this.python(),[join(this.root,'desktop/music-setup.py'),this.home],{...this.env(),PYTHONUNBUFFERED:'1'},this.home);return this.status();}
 async start(){if(!this.installed)throw Error('Instale o motor e os modelos primeiro.');if(this.child)return this.status();this.endpoint='http://127.0.0.1:4326';this.key=randomBytes(32).toString('hex');this.phase='starting';this.error='';this.diagnostic='';const source=join(this.home,'ACE-Step-1.5-'+ACE_REVISION),python=join(source,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');this.launch(python,[join(this.root,'desktop/music-server.py')],{...this.env(),ACESTEP_API_HOST:'127.0.0.1',ACESTEP_API_PORT:'4326',ACESTEP_API_KEY:this.key,ACESTEP_CONFIG_PATH:'acestep-v15-turbo',ACESTEP_INIT_LLM:'false',ACESTEP_NO_INIT:'false',ACESTEP_LM_BACKEND:'pt',ACESTEP_OFFLOAD_TO_CPU:'true',HF_HUB_OFFLINE:'1',TRANSFORMERS_OFFLINE:'1',HF_HUB_DISABLE_TELEMETRY:'1',DO_NOT_TRACK:'1',PYTHONUNBUFFERED:'1'},source);return this.status();}
 configure(input:unknown){if(this.child||this.busy)throw Error('Pare o motor antes de trocar a conexão.');const v=z.strictObject({endpoint:z.string().max(150).transform(musicEndpoint)}).parse(input);this.endpoint=v.endpoint;this.key='';mkdirSync(this.home,{recursive:true,mode:0o700});writeFileSync(join(this.home,'connection.json'),JSON.stringify(v),{mode:0o600});return this.status();}
 private async request(path:string,body?:unknown,signal?:AbortSignal){const r=await fetch(this.endpoint+path,{method:body?'POST':'GET',redirect:'error',headers:{'Content-Type':'application/json',...(this.key?{Authorization:'Bearer '+this.key}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(15000)]):AbortSignal.timeout(5000)});if(!r.ok)throw Error('ACE-Step respondeu HTTP '+r.status);const text=await r.text();if(text.length>2*1024**2)throw Error('Resposta do motor muito grande.');const v=JSON.parse(text);if(v.error||v.code&&v.code!==200)throw Error(String(v.error||'Falha no motor').slice(0,500));return v.data;}
 async check(){try{const data=await this.request('/v1/model_inventory').catch(e=>{if(e.message.includes('HTTP 404'))return this.request('/v1/models');throw e;});const models=z.array(z.object({name:z.string().min(1).max(100),is_default:z.boolean().optional(),is_loaded:z.boolean().optional()})).max(30).parse(data.models).filter(m=>m.is_loaded!==false);if(!models.length)return {connected:false,models:[],error:'O motor está preparando os modelos.'};this.phase='ready';return {connected:true,models};}catch(e){return {connected:false,models:[],error:'Motor indisponível: '+(e as Error).message};}}
 async generate(input:unknown){if(this.busy)throw Error('Aguarde a música atual.');const v=musicRequest.parse(input);this.controller=new AbortController();try{const check=await this.check();if(!check.connected||!check.models.some(m=>m.name===v.model))throw Error(check.error||'Selecione um modelo carregado no motor.');this.controller.signal.throwIfAborted();}catch(e){this.controller=null;throw e;}const signal=this.controller.signal;this.job={id:randomUUID(),state:'running',prompt:v.prompt,model:v.model,at:Date.now()};this.save();this.pending=this.perform(v,signal).catch(e=>{this.job!.state='error';this.job!.error=(e as Error).message;this.save();}).finally(()=>{this.controller=null;this.pending=null;});return this.status();}
 private save(){writeFileSync(join(this.galleryDirectory,'active.json'),JSON.stringify(this.job),{mode:0o600});}
 private async perform(v:z.infer<typeof musicRequest>,signal:AbortSignal){const job=this.job!;const task=await this.request('/release_task',{prompt:v.prompt,lyrics:v.instrumental?'[Instrumental]':v.lyrics,model:v.model,audio_duration:v.duration,bpm:v.bpm,vocal_language:v.language,audio_format:'wav',batch_size:1,inference_steps:v.model.includes('turbo')?8:32,thinking:false,use_cot_caption:false,use_cot_language:false,use_random_seed:v.seed===undefined,seed:v.seed??-1},signal);job.task=z.string().min(1).max(200).parse(task.task_id);this.save();const until=Date.now()+30*60*1000;
  while(Date.now()<until){await delay(2000,undefined,{signal});const result=await this.request('/query_result',{task_id_list:[job.task]},signal);const row=Array.isArray(result)?result.find((r:any)=>r.task_id===job.task):null;if(!row)throw Error('O motor não encontrou esta geração.');if(row.status===2)throw Error('O motor não conseguiu gerar a música. Confira seu diagnóstico.');if(row.status!==1)continue;const items=JSON.parse(row.result);const u=new URL(z.string().parse(items[0]?.file),this.endpoint);if(u.origin!==this.endpoint||u.pathname!=='/v1/audio'||u.username||u.password)throw Error('Endereço de áudio inesperado no motor.');const response=await fetch(u,{redirect:'error',headers:this.key?{Authorization:'Bearer '+this.key}:{},signal:AbortSignal.any([signal,AbortSignal.timeout(120000)])});if(!response.ok||!response.body)throw Error('Falha ao salvar áudio.');const chunks:Buffer[]=[];let size=0;for await(const b of response.body as any){size+=b.length;if(size>128*1024**2)throw Error('Áudio excede 128 MiB.');chunks.push(Buffer.from(b));}const audio=Buffer.concat(chunks);if(audio.toString('ascii',0,4)!=='RIFF'||audio.toString('ascii',8,12)!=='WAVE')throw Error('O motor não retornou um WAV válido.');const file=join(this.galleryDirectory,job.id+'.wav');writeFileSync(file+'.part',audio,{mode:0o600});renameSync(file+'.part',file);job.state='complete';job.file='/v1/music/artifacts/'+job.id;writeFileSync(join(this.galleryDirectory,job.id+'.json'),JSON.stringify(job),{mode:0o600});this.save();return;}throw Error('Tempo limite de 30 minutos. Verifique o motor antes de tentar novamente.');
 }
 gallery(){return readdirSync(this.galleryDirectory).filter(f=>/^[a-f0-9-]{36}\.json$/.test(f)).map(f=>{try{return JSON.parse(readFileSync(join(this.galleryDirectory,f),'utf8'));}catch{return null;}}).filter(Boolean).sort((a,b)=>b.at-a.at).slice(0,100);}
 artifact(id:string){z.string().uuid().parse(id);const file=join(this.galleryDirectory,id+'.wav');if(!existsSync(file)||statSync(file).size>128*1024**2)throw Error('Áudio não encontrado.');return file;}
 async stop(){this.controller?.abort(Error(this.running?'Motor interrompido.':'Acompanhamento interrompido. O servidor externo pode continuar gerando.'));const child=this.child;if(child?.pid){const end=new Promise<void>(r=>child.once('close',()=>r()));const kill=(signal:NodeJS.Signals)=>{try{if(process.platform==='win32'){execFile('taskkill',['/pid',String(child.pid),'/T',...(signal==='SIGKILL'?['/F']:[])],()=>{});}else process.kill(-child.pid!,signal);}catch{}};kill('SIGTERM');const timer=setTimeout(()=>kill('SIGKILL'),5000);await end;clearTimeout(timer);}await this.pending;this.phase=this.installed?'installed':'idle';this.key='';return this.status();}
}
