import {Updates} from './updates.js';
import {Music} from './music.js';
import {Editor} from './editor.js';
import {ComputerControl} from './computer-control.js';
import {Connections} from './connections.js';
import { ExperienceJobs } from './experience-jobs.js';
import { Experience, botTemplates } from './experience.js';
import { recommendations, hardware } from './recommendations.js';
import { MediaDownloads } from './media-downloads.js';
import { Subscription, subscriptionConfig, ProRequired, requiredFeature } from './subscription.js';
import { optimizationSchema, optimizeContext } from './optimization.js';
import { prepareAttachment, attachmentSchema } from "./chat-context.js";
import { ProMedia } from './pro-media.js';
import { Pro } from './pro.js';
import { HFAccount } from './hf-access.js';
import { searchHF,hfVersions,HF_BRANDS } from './huggingface.js';
import { AuxRuntime } from './aux-runtime.js';
import { LocalRuntime } from './runtime.js';
import { Toolbox,accessSchema } from './agent-tools.js';
import { agentReply } from './agent.js';
import { complete } from './inference.js';
import Fastify from 'fastify';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Gateway } from './gateway.js';
import { optionsSchema } from './inference.js';
import { memoryStatus } from './model.js';
import { totalmem } from 'node:os';
import { Chats } from './chat.js';
import { Core } from './core.js';
import { localModels } from './model.js';
import { ModelLibrary } from './model-library.js';
import { acquireProcessLock } from './lock.js';
import { verifyPackage } from '../scripts/protocol.mjs';
import { z } from 'zod';

const equal = (a: string, b: string) => { const left = Buffer.from(a), right = Buffer.from(b); return left.length === right.length && timingSafeEqual(left,right); };
export async function createApp(core: Core, token = randomBytes(32).toString('hex'), origin = 'http://127.0.0.1:4317', runtime = new LocalRuntime(core.directory,core.root), planConfig = subscriptionConfig(core.root)) {
  const app = Fastify({ logger: false, bodyLimit: 2 * 1024 * 1024, ajv: { customOptions: { removeAdditional: false } } });
  const subscription=new Subscription(core.directory,planConfig);
  const aux=new AuxRuntime(core.directory,core.root);
  const proMedia=new ProMedia(core.directory,core.root);
  const toolbox=new Toolbox(core.directory);
  const computerControl=new ComputerControl();toolbox.computerControl=computerControl;
  const connections=new Connections(core.directory,core.vault,origin);toolbox.connections=connections;
  const hfAccount=new HFAccount(core.directory,core.vault);
  const mediaDownloads=new MediaDownloads(core.directory,()=>hfAccount.token());
  const library = new ModelLibrary(core.directory, (type, data) => core.store.tx((state, entries) => { if (!state || core.vault.locked) throw new Error('Cofre bloqueado'); core.append(state, entries, type, data); }),undefined,runtime,()=>hfAccount.token());
  const experience=new Experience(core);
  const updates=new Updates(core.directory,JSON.parse(readFileSync(join(core.root,'package.json'),'utf8')).version);
  const personality=async()=>Boolean((await experience.snapshot()).personality);
  const music=new Music(core.directory,core.root);
  const editor=new Editor(core.root,async(key,prompt,signal)=>exclusive(async()=>{if(core.vault.locked||chats.busy||aux.busy||pro.busy||gateway.status().enabled||experienceJobs.busy||music.running||music.busy)throw Error('Aguarde a IA atual e desligue o motor de música antes de preparar a edição.');const m=await library.load(key,8192);const result=await complete(m.instance_id,[{role:'user',content:prompt}],optionsSchema.parse({context:8192,max_tokens:3000,temperature:.2,reasoning:'off'}),signal,()=>{},runtime.backend(m.instance_id));return result.text;}));
  const chats = new Chats(core,agentReply(runtime,toolbox,personality));
  if (!core.vault.locked) await chats.recover();
  let operationBusy=false;
  let experienceJobs:ExperienceJobs;
  let pro:Pro;

  const gateway=new Gateway(core.directory,()=>!music.busy&&!music.running&&!editor.busy&&!core.vault.locked&&!chats.busy&&!core.jobs.size&&!operationBusy&&!aux.busy&&!proMedia.busy&&!pro?.busy&&!experienceJobs?.busy,(model,messages,options,signal,delta)=>complete(model,messages,options,signal,delta,runtime.backend(model)),4320,core.root,()=>subscription.active);
  pro=new Pro(core.directory,{models:async()=>(await library.snapshot()).installed,canRun:()=>!music.busy&&!music.running&&!editor.busy&&!experienceJobs?.busy&&subscription.active&&!core.vault.locked&&!operationBusy&&!chats.busy&&!gateway.busy&&!aux.busy&&!proMedia.busy&&!core.jobs.size&&!library.busy,run:async(key,messages,options,signal,delta)=>exclusive(async()=>{signal.throwIfAborted();if(core.vault.locked||chats.busy||gateway.busy||aux.busy)throw Error('Aguarde o motor atual.');if(gateway.status().enabled&&gateway.status().local_model!==key)throw Error('Desligue Minha API antes de executar outra IA no Pro.');subscription.require('jobs');const model=await library.load(key,options.context);signal.throwIfAborted();const result=await agentReply(runtime,toolbox,personality)(model.instance_id,messages.filter(m=>m.role==='user'||m.role==='assistant').map((m,i)=>({id:String(i),role:m.role as 'user'|'assistant',content:m.content,at:Date.now(),status:'complete' as const})),signal,delta,{...options,system:messages.filter(m=>m.role==='system').map(m=>m.content).join('\n')||options.system},{chatId:'pro-job',access:{enabled:false},activity:()=>{}});return typeof result==='string'?result:result.text;})});
  experienceJobs=new ExperienceJobs(experience,async(key,prompt,options,signal,delta,bot)=>exclusive(async()=>{signal.throwIfAborted();if(core.vault.locked)throw Error('Cofre bloqueado');const model=await library.load(key,options.context);signal.throwIfAborted();return agentReply(runtime,toolbox,personality)(model.instance_id,[{id:'experience',role:'user',content:prompt,at:Date.now(),status:'complete'}],signal,delta,options,{chatId:'experience',privateContext:false,access:{enabled:false},activity:()=>{}});}),()=>!music.busy&&!music.running&&!editor.busy&&!core.vault.locked&&!operationBusy&&!chats.busy&&!pro.busy&&!gateway.status().enabled&&!gateway.busy&&!aux.busy&&!proMedia.busy&&!core.jobs.size&&!library.busy,core.directory);
  let modelGate = Promise.resolve();
  function exclusive<T>(operation: () => Promise<T>): Promise<T> {
    const result = modelGate.then(async()=>{operationBusy=true;try{return await operation();}finally{operationBusy=false;}}); modelGate = result.then(() => {}, () => {}); return result;
  }
  app.addHook('preClose',async()=>{await editor.close();await music.stop();await computerControl.stop();await connections.close();await experienceJobs.stop();await mediaDownloads.pause();await pro.close();await proMedia.close();await aux.close();});
  app.addHook('onClose', async () => { await exclusive(async () => { await aux.close(); await gateway.stop(); await chats.close(); await library.stop(); }); });
  const staticFiles: Record<string, [string,string]> = { '/ux.js':['ux.js','application/javascript'], '/ux.css':['ux.css','text/css'], '/creative.js':['creative.js','application/javascript'], '/creative.css':['creative.css','text/css'], '/experience.js':['experience.js','application/javascript'], '/experience.css':['experience.css','text/css'], '/photo.js':['photo.js','application/javascript'], '/exo.js':['exo.js','application/javascript'], '/exo.css':['exo.css','text/css'], '/app-icon.png':['app-icon.png','image/png'], '/polish.css':['polish.css','text/css'], '/mascot.png':['mascot.png','image/png'], '/mascot-thinking.png':['mascot-thinking.png','image/png'], '/mascot-success.png':['mascot-success.png','image/png'], '/mascot-attention.png':['mascot-attention.png','image/png'], '/mascot.js':['mascot.js','application/javascript'], '/mascot.css':['mascot.css','text/css'], '/premium-experience.js':['premium-experience.js','application/javascript'], '/premium-experience.css':['premium-experience.css','text/css'], '/pro-center.js':['pro-center.js','application/javascript'], '/model-icons.js':['model-icons.js','application/javascript'], '/model-identities.js':['model-identities.js','application/javascript'], '/media-library.js':['media-library.js','application/javascript'], '/subscription.js':['subscription.js','application/javascript'], '/subscription.css':['subscription.css','text/css'], "/chat-assist.js":["chat-assist.js","application/javascript"], "/chat-assist.css":["chat-assist.css","text/css"], '/studio-pro.js':['studio-pro.js','application/javascript'], '/pro.js':['pro.js','application/javascript'], '/pro.css':['pro.css','text/css'], '/': ['index.html','text/html; charset=utf-8'], '/app.js': ['app.js','application/javascript'], '/chat.js': ['chat.js','application/javascript'], '/styles.css': ['styles.css','text/css'], '/sharing.js':['sharing.js','application/javascript'], '/theme.css':['theme.css','text/css'], '/workspace.css':['workspace.css','text/css'], '/professional.css':['professional.css','text/css'], '/icons.js':['icons.js','application/javascript'], '/voice.js':['voice.js','application/javascript'], '/audio-worklet.js':['audio-worklet.js','application/javascript'], '/studio.js':['studio.js','application/javascript'], '/studio-project.js':['studio-project.js','application/javascript'], '/studio-renderer.js':['studio-renderer.js','application/javascript'], '/studio.css':['studio.css','text/css'], '/hub.js':['hub.js','application/javascript'], '/vendor/marked.js':['../node_modules/marked/lib/marked.esm.js','application/javascript'], '/vendor/purify.js':['../node_modules/dompurify/dist/purify.es.mjs','application/javascript'] };
  const iconDirectory=join(core.root,'public/model-icons');if(existsSync(iconDirectory))for(const file of readdirSync(iconDirectory)){if(/^[a-f0-9]{24}\.(png|jpg|webp)$/.test(file))staticFiles['/model-icons/'+file]=['model-icons/'+file,file.endsWith('.jpg')?'image/jpeg':file.endsWith('.png')?'image/png':'image/webp'];}
  let failedUnlocks = 0, retryAt = 0;
  app.addHook('onRequest', async (request, reply) => {
    reply.header('X-Content-Type-Options','nosniff').header('Referrer-Policy','no-referrer').header('Cache-Control','no-store');
    reply.header('Content-Security-Policy', "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'none'");
    if (request.headers.host !== new URL(origin).host) return reply.code(403).send({ error: 'Host recusado' });
    const oauthCallback=request.method==='GET'&&request.url.startsWith('/v1/connections/oauth/callback?');
    if(oauthCallback)return;
    if (request.headers.origin && request.headers.origin !== origin) return reply.code(403).send({ error: 'Origem recusada' });
    if (request.headers['sec-fetch-site'] === 'cross-site') return reply.code(403).send({ error: 'Origem externa recusada' });
    if (staticFiles[request.url] && request.method === 'GET') return;
    const bearer = request.headers.authorization?.replace(/^Bearer /, '') ?? '';
    const cookie = request.headers.cookie?.split('; ').find(v => v.startsWith('colmeia='))?.slice(8) ?? '';
    if (!equal(bearer, token) && !equal(cookie, token)) return reply.code(401).send({ error: 'Abra a aplicação pelo iniciador local para autenticar esta sessão.' });
    if((music.busy||music.running||editor.busy)&&request.method==='POST'&&/^\/v1\/(experience\/bots\/.*\/run|chats\/.*\/send|model-library\/(load|unload|engine|import-mlx)|sharing\/start|tasks\/.*\/start|pro\/(jobs|media\/.*)|local-engines\/(generate|transcribe)|experience\/(room|benchmark))$/.test(request.url))return reply.code(409).send({error:'Pare o motor de música ou aguarde o Editor antes de iniciar outra IA.'});
    if(experienceJobs.busy&&request.method!=='GET'&&!/^\/v1\/(experience\/(room|benchmark)\/stop|assistant\/approve|lock)$/.test(request.url))return reply.code(409).send({error:'Pare o teste ou a reunião antes de iniciar outra operação.'});
    if(pro.busy&&request.method==='POST'&&/^\/v1\/(experience\/bots\/.*\/run|chats\/.*\/send|model-library\/(load|unload|engine|import-mlx)|sharing\/start|tasks\/.*\/start|local-engines\/(generate|transcribe))$/.test(request.url))return reply.code(409).send({error:'Aguarde a tarefa Pro ou cancele-a na fila.'});
    if((aux.busy||proMedia.busy)&&request.method==='POST'&&/\/chats\/[^/]+\/send$/.test(request.url))return reply.code(409).send({error:'Aguarde o motor de voz ou imagem.'});
    if (!['/v1/status','/v1/setup','/v1/unlock','/v1/session'].includes(request.url) && core.vault.locked) return reply.code(423).send({ error: 'Desbloqueie o cofre para continuar.' });
  });
  app.addHook('preHandler',async(request)=>{const feature=requiredFeature(request.method,request.routeOptions.url||request.url.split('?')[0],request.body);if(feature)subscription.require(feature);});
  app.setErrorHandler((error, _request, reply) => {
    if(error instanceof ProRequired)return reply.code(402).send({error:error.message,code:'pro_required',feature:error.feature});
    const err = error as Error;
    const message = err instanceof z.ZodError ? 'Dados inválidos: ' + err.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; ') : err.message;
    const conflict = /Conflito|Versão mudou|Idempotency-Key reutilizada|imutável/.test(message);
    reply.code(conflict ? 409 : 400).send({ error: message });
  });
  for (const [route, [file,type]] of Object.entries(staticFiles)) app.get(route, async (_request, reply) => reply.type(type).send(readFileSync(join(core.root,'public',file))));
  const body = (request: any) => request.body as any;
  const key = (request: any) => String(request.headers['idempotency-key'] ?? '');
  const id = (request: any) => String(request.params.id);
  let lastPlanRefresh=0;
  app.get('/v1/subscription',async()=>{const state=subscription.snapshot();if(state.configured&&state.checked_at&&Date.now()-state.checked_at>86400_000&&Date.now()-lastPlanRefresh>1800_000){lastPlanRefresh=Date.now();void subscription.refresh().catch(()=>{});}return state;});
  app.post('/v1/subscription/refresh',async()=>subscription.refresh());
  app.post('/v1/subscription/checkout',async()=>subscription.checkout());
  app.post('/v1/subscription/portal',async()=>subscription.portal());
  app.post('/v1/subscription/studio',async()=>({ok:true}));
  app.post('/v1/pro/optimize',async request=>{const v=optimizationSchema.parse(body(request));const model=(await library.snapshot()).installed.find(m=>m.key===v.key);if(!model)throw Error('Escolha um modelo instalado.');const result=optimizeContext(model,memoryStatus().available_memory_bytes,v.mode,v.options);pro.profile(v.key,result.options);return result;});
  app.get('/v1/pro/media',async()=>proMedia.status());
  app.post('/v1/pro/media/install-voice',async()=>proMedia.install());
  app.post('/v1/pro/media/stop',async()=>{await proMedia.close();aux.stop();return {ok:true};});
  app.post('/v1/pro/media/speak',async request=>exclusive(async()=>{if(core.vault.locked||pro.busy||chats.busy||gateway.busy||aux.busy)throw Error('Aguarde o motor atual.');const v=z.object({text:z.string().trim().min(1).max(4000),speed:z.number().min(.5).max(2).default(1)}).parse(body(request));return proMedia.speak(v.text,v.speed);}));
  app.get('/v1/pro/media/audio/:id',async(request,reply)=>reply.type('audio/wav').send(proMedia.audio(id(request))));
  app.post('/v1/pro/media/inpaint',{bodyLimit:15*1024**2},async request=>exclusive(async()=>{if(core.vault.locked||pro.busy||chats.busy||gateway.busy||aux.busy||proMedia.busy)throw Error('Aguarde o motor atual.');const v=z.object({prompt:z.string().min(1).max(4000),image:z.string().max(7*1024**2),mask:z.string().max(7*1024**2),steps:z.number().int().min(4).max(40).default(20),strength:z.number().min(.1).max(1).default(.75)}).parse(body(request));return aux.generate('sd15',v.prompt,v.steps,{image:Buffer.from(v.image,'base64'),mask:Buffer.from(v.mask,'base64'),strength:v.strength});}));
  app.get('/v1/pro',async()=>pro.snapshot());
  app.post('/v1/pro/queue',async request=>pro.queue(z.strictObject({paused:z.boolean()}).parse(body(request)).paused));
  app.post('/v1/pro/jobs/:id/priority',async request=>pro.prioritize(id(request),z.strictObject({priority:z.number().int().min(0).max(2)}).parse(body(request)).priority));
  app.post('/v1/pro/templates',async request=>pro.template(body(request)));
  app.delete('/v1/pro/templates/:id',async request=>pro.removeTemplate(id(request)));

  app.post('/v1/pro/projects',async request=>pro.project(body(request)));
  app.delete('/v1/pro/projects/:id',async request=>pro.removeProject(id(request)));
  app.post('/v1/pro/assistants',async request=>pro.assistant(body(request)));
  app.delete('/v1/pro/assistants/:id',async request=>pro.removeAssistant(id(request)));
  app.post('/v1/pro/documents',{bodyLimit:18*1024**2},async request=>pro.document(body(request)));
  app.delete('/v1/pro/documents/:id',async request=>pro.removeDocument(id(request)));
  app.post('/v1/pro/search',async request=>{const v=z.object({project:z.string().uuid(),query:z.string().max(2000)}).parse(body(request));return pro.search(v.project,v.query);});
  app.post('/v1/pro/jobs',async request=>pro.enqueue(body(request)));
  app.post('/v1/pro/jobs/:id/cancel',async request=>pro.cancel(id(request)));
  app.post('/v1/pro/automations',async request=>pro.automation(body(request)));
  app.get('/v1/pro/diagnostics',async()=>pro.diagnostics());
  app.post('/v1/pro/profiles',async request=>{const v=z.object({key:z.string().max(512),options:optionsSchema}).parse(body(request));return pro.profile(v.key,v.options);});
  app.get('/v1/pro/projects/:id/export/:format',async(request,reply)=>{const {format}=z.object({format:z.enum(['md','docx','xlsx','pptx'])}).parse(request.params);const file=await pro.export(id(request),format);return reply.type(file.type).header('Content-Disposition',`attachment; filename="localneuron.${file.ext}"`).send(file.buffer);});
  app.get('/v1/pro/backups',async()=>pro.backups());
  app.get('/v1/pro/backups/:id',async(request,reply)=>reply.type('application/json').header('Content-Disposition','attachment; filename=LocalNeuron-backup.json').send(pro.backupFile(id(request))));
  app.post('/v1/pro/backup',{bodyLimit:180*1024**2},async request=>{const v=z.object({password:z.string().min(12).max(1024),studio:z.unknown()}).parse(body(request));return pro.backup(v.password,v.studio);});
  for(const action of ['inspect','restore'] as const)app.post('/v1/pro/backup/'+action,{bodyLimit:245*1024**2},async request=>{const v=z.object({password:z.string().max(1024),backup:z.unknown()}).parse(body(request));return action==='inspect'?pro.inspectBackup(v.backup,v.password):pro.restore(v.backup,v.password);});
  app.get('/v1/huggingface/brands',async()=>({brands:HF_BRANDS}));
  app.get('/v1/huggingface/account',async()=>hfAccount.status());
  app.post('/v1/huggingface/account',async request=>{const {token}=z.strictObject({token:z.string().max(220)}).parse(body(request));return hfAccount.connect(token);});
  app.delete('/v1/huggingface/account',async()=>{if(library.active||mediaDownloads.busy)throw Error('Pause o download antes de desconectar a conta.');return hfAccount.disconnect();});
  app.post('/v1/model-library/check',async request=>{const {id}=z.strictObject({id:z.string().max(60)}).parse(body(request));return library.access.check((()=>{const m=library.catalog.find(m=>m.id===id);if(!m)throw Error('Modelo não encontrado');return m;})());});
  app.get('/v1/huggingface',async request=>{const q=z.object({author:z.string().max(80).default('Qwen'),query:z.string().max(120).default(''),cursor:z.string().max(2000).optional()}).parse(request.query);return searchHF(q.author,q.query,q.cursor,hfAccount.token());});
  app.post('/v1/huggingface/versions',async request=>{const {repo}=z.strictObject({repo:z.string().max(180)}).parse(body(request));return hfVersions(repo,hfAccount.token());});
  app.post('/v1/huggingface/add',async request=>{const {repo,variant}=z.strictObject({repo:z.string().max(180),variant:z.string().regex(/^[a-f0-9]{20}$/).optional()}).parse(body(request));return library.addHF(repo,variant);});
  const exoIdle=()=>{if(chats.busy||gateway.busy||gateway.status().enabled||pro.busy||core.jobs.size||library.busy||aux.busy||proMedia.busy)throw Error('Aguarde a IA terminar e desligue Minha API antes de alterar a Rede EXO.');};
  app.get('/v1/exo',async()=>{await runtime.exo.refresh();return runtime.exo.snapshot();});
  app.post('/v1/exo/config',async request=>exclusive(async()=>{exoIdle();return runtime.exo.configure(body(request));}));
  app.post('/v1/exo/install',async()=>{exoIdle();return runtime.exo.installer.install();});
  app.post('/v1/exo/install/cancel',async()=>runtime.exo.installer.cancel());
  app.post('/v1/exo/start',async()=>exclusive(async()=>{exoIdle();return runtime.exo.start();}));
  app.post('/v1/exo/stop',async()=>exclusive(async()=>{exoIdle();return runtime.exo.stop();}));
  app.post('/v1/exo/prepare',async request=>exclusive(async()=>{exoIdle();const v=z.strictObject({model:z.string().min(1).max(400),nodes:z.number().int().min(1).max(128),sharding:z.enum(['Pipeline','Tensor']).default('Pipeline'),selected:z.array(z.string().min(1).max(150)).max(128).default([])}).parse(body(request));return runtime.exo.prepare(v.model,v.nodes,v.sharding,v.selected);}));
  app.post('/v1/exo/remove',async request=>exclusive(async()=>{exoIdle();const v=z.strictObject({id:z.string().min(1).max(150)}).parse(body(request));return runtime.exo.remove(v.id);}));
  app.get('/v1/engines',async()=>({engines:[{name:'EXO',use:'Texto · execução distribuída entre máquinas',available:runtime.exo.connected,requirement:'Abra Rede EXO. Mac Apple Silicon com macOS 26.2+ para o motor gerenciado; outros sistemas podem conectar um servidor EXO compatível.'},{name:'llama.cpp',use:'Conversa, escrita e código · GGUF',available:runtime.ggufAvailable,requirement:'Mac ARM64/Metal, Windows x64/CPU, Linux x64/CPU. Arquitetura e quantização precisam ser compatíveis.'},{name:'MLX + MLX LM',use:'Texto · pastas MLX',available:runtime.mlxAvailable,requirement:'Somente Mac com Apple Silicon. Importação de pasta MLX no Chat.'},...aux.snapshot().engines.map(e=>({name:e.name==='whisper'?'whisper.cpp':'stable-diffusion.cpp',use:e.name==='whisper'?'Transcrição · modelos Whisper do Estúdio':'Imagem SD 1.5 e vídeo Wan 2.1 do Estúdio',available:e.available,requirement:e.name==='whisper'?'Perfis tiny, base, small e medium.':'Perfis integrados específicos; macOS 26+, Windows x64 ou Linux compatível.'})),{name:'sherpa-onnx / Piper',use:'Síntese de voz · português',available:existsSync(join(core.root,'runtime','voice-node-'+process.platform+'-'+process.arch,process.platform==='win32'?'node.exe':'node')),requirement:'Perfil de voz Faber. Baixe a voz em Ler respostas antes de usar.'}]}));
  app.get('/v1/local-engines',async()=>aux.snapshot());
  app.get('/v1/local-engines/gallery',async()=>aux.gallery());
  app.post('/v1/local-engines/download',async request=>{const {id}=z.strictObject({id:z.string().max(100)}).parse(body(request));if(mediaDownloads.busy||library.active)throw Error('Pause o outro download antes de iniciar este.');return aux.startDownload(id);});
  app.post('/v1/local-engines/cancel-download',async()=>{await aux.cancelDownload();return {ok:true};});
  app.post('/v1/local-engines/stop',async()=>{aux.stop();return {ok:true};});
  app.post('/v1/local-engines/transcribe',{bodyLimit:4*1024*1024},async request=>exclusive(async()=>{if(core.vault.locked||core.jobs.size||chats.busy||gateway.busy||runtime.busy)throw new Error('Aguarde a IA terminar antes de transcrever.');const {model,audio,language}=z.strictObject({model:z.string().max(100),language:z.enum(['pt','en','es','auto']).default('pt'),audio:z.string().min(1).max(3840064).regex(/^[A-Za-z0-9+/]+={0,2}$/)}).parse(body(request));return aux.transcribe(model,Buffer.from(audio,'base64'),language);}));
  app.post('/v1/local-engines/generate',async request=>exclusive(async()=>{if(core.vault.locked||core.jobs.size||chats.busy||gateway.busy||runtime.busy)throw new Error('Aguarde a IA terminar antes de gerar mídia.');const {model,prompt,steps,...options}=z.strictObject({model:z.string().max(100),prompt:z.string().trim().min(1).max(4000),steps:z.number().int().min(4).max(40).default(20),seed:z.number().int().min(0).max(2147483646).optional(),negative:z.string().max(2000).optional(),aspect:z.enum(['1:1','16:9','9:16']).default('1:1')}).parse(body(request));return aux.generate(model,prompt,steps,options);}));
  app.get('/v1/local-engines/artifacts/:id',async(request,reply)=>{const artifact=aux.artifact(String((request.params as any).id));return reply.type(artifact.type).header('Content-Disposition','inline').send(readFileSync(artifact.file));});
  app.post('/v1/session', async (_request, reply) => reply.header('Set-Cookie', `colmeia=${token}; HttpOnly; SameSite=Strict; Path=/`).send({ ok: true }));
  app.get('/v1/status', async () => core.status());
  for (const route of ['setup','unlock'] as const) app.post('/v1/' + route, async request => {
    if (Date.now() < retryAt) throw new Error('Aguarde antes de tentar outra senha');
    const { password } = z.strictObject({ password: z.string().min(1).max(1024) }).parse(body(request));
    try { await core[route](password); await chats.recover(); failedUnlocks = 0; return { ok: true }; }
    catch (error) { failedUnlocks++; if (failedUnlocks >= 3) retryAt = Date.now() + 30000; throw error; }
  });
  app.post('/v1/experience/templates',async request=>botTemplates(z.strictObject({use:z.enum(['personal','work','both'])}).parse(body(request)).use));
  app.get('/v1/experience/benchmark',async()=>experienceJobs.benchmark);
  app.post('/v1/experience/benchmark',async request=>experienceJobs.test(z.strictObject({key:z.string().min(1).max(512)}).parse(body(request)).key));
  app.post('/v1/experience/benchmark/stop',async()=>experienceJobs.stop());
  app.get('/v1/experience/room',async()=>experienceJobs.room);
  app.post('/v1/experience/room',async request=>experienceJobs.collaborate(body(request)));
  app.post('/v1/experience/room/stop',async()=>experienceJobs.stop());
  app.get('/v1/connections/oauth/callback',async(request,reply)=>{const v=z.object({state:z.string().min(32).max(128),code:z.string().min(1).max(4096)}).parse(request.query);await connections.callback(v.state,v.code);return reply.type('text/plain; charset=utf-8').send('Autorização recebida. Volte ao LocalNeuron e atualize Conexões.');});
  app.get('/v1/computer-control',async()=>computerControl.status());
  app.post('/v1/computer-control',async request=>{const v=z.strictObject({enabled:z.boolean()}).parse(body(request));if(!v.enabled)return computerControl.stop();if(!computerControl.available)throw Error('Abra o aplicativo desktop para usar este controle.');computerControl.enabled=true;return computerControl.status();});
  app.get('/v1/connections',async()=>connections.list());
  app.post('/v1/connections',async request=>connections.add(body(request)));
  app.post('/v1/connections/:id/test',async request=>{if(chats.busy)throw Error('Pare a resposta antes de reconectar.');return connections.test(id(request));});
  app.delete('/v1/connections/:id',async request=>connections.remove(id(request)));
  app.get('/v1/personality',async()=>({enabled:await personality()}));
  app.post('/v1/personality',async request=>experience.personality(body(request),key(request)));
  app.get('/v1/editor',async()=>editor.status());
  app.post('/v1/editor/plan',async request=>editor.propose(body(request)));
  app.post('/v1/editor/apply',async request=>editor.apply(body(request)));
  app.post('/v1/editor/stop',async()=>{await editor.close();return {ok:true};});
  app.get('/v1/music',async()=>music.status());
  app.get('/v1/music/models',async()=>music.check());
  app.get('/v1/music/gallery',async()=>music.gallery());
  app.get('/v1/music/artifacts/:id',async(request,reply)=>reply.type('audio/wav').send(readFileSync(music.artifact(id(request)))));
  const musicIdle=(inside=false)=>{if(core.vault.locked||(!inside&&operationBusy)||chats.busy||aux.busy||proMedia.busy||pro.busy||gateway.status().enabled||gateway.busy||experienceJobs.busy||editor.busy||core.jobs.size||library.busy)throw Error('Aguarde a IA atual antes de usar música.');};
  app.post('/v1/music/install',async()=>{musicIdle();return music.install();});
  app.post('/v1/music/start',async()=>{musicIdle();return exclusive(async()=>{musicIdle(true);for(const model of runtime.status().models)await runtime.unload(model);return music.start();});});
  app.post('/v1/music/connection',async request=>music.configure(body(request)));
  app.post('/v1/music/generate',async request=>{musicIdle();return music.generate(body(request));});
  app.post('/v1/music/stop',async()=>music.stop());
  app.get('/v1/updates',async()=>updates.status());
  app.post('/v1/updates/check',async request=>updates.check(z.strictObject({force:z.boolean().default(false)}).parse(body(request)).force));
  app.post('/v1/updates/preferences',async request=>updates.preferences(body(request)));
  app.post('/v1/updates/dismiss',async request=>updates.dismiss(body(request)));
  app.post('/v1/experience/playbooks',async request=>experience.upgrade(key(request)));
  app.post('/v1/experience/deploy',async request=>{
    const v=z.strictObject({use:z.enum(['personal','work','both']),model:z.string().max(512).optional()}).parse(body(request));
    if(chats.busy)throw Error('Aguarde a tarefa atual antes de ativar a equipe.');
    const exp=await experience.snapshot(),models=(await library.snapshot()).installed;
    const candidate=v.model||exp.profile.selected_model;
    let selected=models.find(m=>m.key===candidate);
    if(v.model&&!selected)throw Error('Escolha um modelo instalado.');
    if(!selected){const rec=await recommendations(library,aux,core.directory,'chat',exp.profile.objectives);selected=models.find(m=>m.key===rec.models.filter(r=>r.installed).sort((a,b)=>b.bytes-a.bytes)[0]?.key);}
    if(!selected)throw Error('Instale uma IA compatível em Modelos para ativar sua equipe. Nenhum download foi iniciado.');
    const deployKey=z.string().regex(/^[a-zA-Z0-9_-]{8,90}$/).parse(key(request));
    await experience.upgrade(deployKey+'-methods');
    const bots=await experience.suggest({use:v.use,model:selected.key},deployKey);
    return {bots,model:selected.key};
  });
  app.post('/v1/experience/bots/:id/run',async request=>exclusive(async()=>{
    const v=z.strictObject({objective:z.string().trim().min(1).max(12000)}).parse(body(request));
    if(chats.busy||aux.busy||proMedia.busy||pro.busy||experienceJobs.busy||gateway.status().enabled||gateway.busy||core.jobs.size||library.busy||music.running||music.busy||editor.busy)throw Error('Aguarde a tarefa atual ou pare o outro motor antes de começar.');
    const requestKey=z.string().regex(/^[a-zA-Z0-9_-]{8,90}$/).parse(key(request));
    const bot=(await experience.snapshot()).bots.find(b=>b.id===id(request));if(!bot)throw Error('Bot não encontrado.');
    if(!bot.model)throw Error('Ative a equipe com uma IA instalada primeiro.');
    const loaded=await library.load(bot.model,8192);
    const chat=await chats.create(requestKey+'-chat',{bot_id:bot.id,preferred_model:bot.model});
    await chats.send(chat.id,loaded.instance_id,v.objective,requestKey+'-send',optionsSchema.parse({context:8192,max_tokens:2048,reasoning:'off'}),false,bot.access,[],bot.model);
    return {id:chat.id,model:bot.model};
  }));
  app.get('/v1/experience',async()=>experience.snapshot());
  app.get('/v1/experience/hardware',async()=>hardware(core.directory));
  app.post('/v1/experience/profile',async request=>experience.profile(body(request),key(request)));
  app.post('/v1/experience/team',async request=>experience.suggest(body(request),key(request)));
  app.post('/v1/experience/bots',async request=>{if(chats.busy)throw Error('Pare a resposta antes de editar permissões.');return experience.bot(body(request),key(request));});
  app.delete('/v1/experience/bots/:id',async request=>experience.remove(id(request)));
  app.post('/v1/experience/recommendations',async request=>{const v=z.strictObject({kind:z.enum(['chat','image','video']),objective:z.string().max(2000).default('')}).parse(body(request));return recommendations(library,aux,core.directory,v.kind,v.objective);});
  app.get('/v1/resources',async()=>({...memoryStatus(),total_memory_bytes:totalmem(),generation_busy:music.busy||editor.busy||chats.busy||gateway.busy||aux.busy,library_busy:library.busy,updated_at:Date.now()}));
  app.post('/v1/sharing/keys',async request=>gateway.addKey(body(request)));
  app.post('/v1/sharing/keys/:id',async request=>gateway.updateKey(id(request),body(request)));
  app.delete('/v1/sharing/keys/:id',async request=>gateway.removeKey(id(request)));
  app.get('/v1/sharing',async()=>gateway.status());
  app.post('/v1/sharing/key',async request=>exclusive(async()=>{if(core.vault.locked)throw new Error('Cofre bloqueado');z.strictObject({}).parse(body(request));return gateway.rotate();}));
  app.post('/v1/sharing/revoke',async request=>{z.strictObject({}).parse(body(request));return gateway.revoke();});
  app.post('/v1/sharing/stop',async request=>{z.strictObject({}).parse(body(request));return gateway.stop();});
  app.post('/v1/sharing/start',async request=>exclusive(async()=>{
    if(gateway.status().enabled)throw new Error('Desligue a API antes de mudar o modelo.');
    if(core.vault.locked||chats.busy||gateway.busy||core.jobs.size)throw new Error('Aguarde a IA terminar antes de compartilhar.');
    const data=z.strictObject({host:z.string().max(50),key:z.string().min(1).max(512),trusted_network:z.boolean().default(false),options:optionsSchema.optional()}).parse(body(request));
    if(data.host!=='127.0.0.1'&&!data.trusted_network)throw new Error('Confirme que esta é uma rede privada confiável ou VPN.');
    if(aux.busy||proMedia.busy)throw new Error('Aguarde o motor de voz ou imagem.');const options=optionsSchema.parse(data.options||{}),model=await library.load(data.key,options.context);return gateway.start(data.host,model.instance_id,options);
  }));
  app.get('/v1/assistant',async()=>toolbox.status());
  app.get('/v1/assistant/artifacts/:id',async(request,reply)=>{const value=await toolbox.artifact(id(request));return reply.type('application/octet-stream').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(value.name)}`).send(value.content);});
  app.post('/v1/assistant/folder',async request=>{if(chats.busy)throw new Error('Pare a resposta antes de trocar a pasta.');const {folder}=z.strictObject({folder:z.string().max(2048).nullable()}).parse(body(request));return toolbox.chooseFolder(folder);});
  app.post('/v1/assistant/approve',async request=>{const {id,allow}=z.strictObject({id:z.string().uuid(),allow:z.boolean()}).parse(body(request));return toolbox.approve(id,allow);});
  app.get('/v1/workspace', async () => core.snapshot());
  app.post('/v1/chats/attachments',{bodyLimit:18*1024**2},async request=>{
    const v=z.strictObject({name:z.string().min(1).max(240),data:z.string().max(16*1024**2).regex(/^[A-Za-z0-9+/]+={0,2}$/)}).parse(body(request));
    return prepareAttachment(v.name,Buffer.from(v.data,'base64'));
  });
  app.post('/v1/chats/:id/memory',async request=>{const v=z.strictObject({memory:z.string().max(6000)}).parse(body(request));return chats.memory(id(request),v.memory);});
  app.post('/v1/chats/:id/fork',async request=>{const v=z.strictObject({message:z.string().uuid(),edit:z.boolean().default(false)}).parse(body(request));return chats.fork(id(request),v.message,v.edit,key(request));});
  app.post('/v1/chats/:id/to-pro',async request=>{const v=z.strictObject({message:z.string().uuid()}).parse(body(request));const chat=(await chats.list()).find(c=>c.id===id(request));const message=chat?.messages.find(m=>m.id===v.message&&m.role==='assistant'&&m.status==='complete');if(!chat||!message)throw Error('Escolha uma resposta concluída.');if(message.content.length>200000)throw Error('Resposta maior que o editor Pro. Copie um trecho menor.');return pro.project({name:chat.title.slice(0,100),body:message.content.slice(0,200000),memory:chat.memory||''});});
  app.get('/v1/chats', async () => chats.list());
  app.post('/v1/chats', async request => { const metadata=z.strictObject({bot_id:z.string().uuid().optional(),preferred_model:z.string().max(512).optional()}).parse(body(request)); return chats.create(key(request),metadata); });
  app.post('/v1/chats/:id/send', {bodyLimit:2*1024**2}, async request => exclusive(async () => {
    const data = z.strictObject({ model: z.string().min(1).max(512), model_key:z.string().max(512).optional(), content: z.string().trim().min(1).max(131072), options:optionsSchema.optional(), retry:z.boolean().default(false),access:accessSchema.optional(),attachments:z.array(attachmentSchema).max(4).default([]) }).parse(body(request));
    if(aux.busy||proMedia.busy)throw new Error('Aguarde o motor de voz ou imagem.');
    if(gateway.busy)throw new Error('A IA está atendendo uma chamada da API. Tente em instantes.');
    return chats.send(id(request), data.model, data.content, key(request), data.options, data.retry,data.access,data.attachments,data.model_key);
  }));
  app.post('/v1/chats/:id/stop', async request => { z.strictObject({}).parse(body(request)); return chats.stop(id(request)); });
  app.post('/v1/chats/:id/rename',async request=>{const {title}=z.strictObject({title:z.string().trim().min(1).max(100)}).parse(body(request));return chats.rename(id(request),title);});
  app.delete('/v1/chats/:id',async request=>chats.remove(id(request)));
  app.get('/v1/models', async () => localModels());
  app.get('/v1/model-library', async () => ({...await library.snapshot(),media_downloads:mediaDownloads.snapshot(),media_profiles:aux.snapshot().models.filter(m=>m.kind!=='speech'),studio_download:aux.download}));
  app.get('/v1/media-downloads',async()=>mediaDownloads.snapshot());
  app.post('/v1/media-downloads',async request=>{const {model,file}=z.strictObject({model:z.string().max(100),file:z.number().int().min(0).max(999)}).parse(body(request));if(library.active||aux.download?.state==='downloading')throw Error('Aguarde ou pause o outro download antes de baixar pesos visuais.');return mediaDownloads.download(model,file);});
  app.post('/v1/media-downloads/pause',async()=>mediaDownloads.pause());
  app.post('/v1/model-library/engine', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); z.strictObject({}).parse(body(request)); return library.startEngine(); }));
  app.post('/v1/model-library/import-mlx', async request => exclusive(async () => {
    if (core.vault.locked || chats.busy || library.busy || gateway.busy) throw new Error('Aguarde a operação atual antes de importar.');
    const {folder}=z.strictObject({folder:z.string().min(1).max(2048)}).parse(body(request));
    const imported=await runtime.importMlx(folder);
    return {key:imported.key,display_name:imported.display_name,size_bytes:imported.size_bytes};
  }));
  app.post('/v1/model-library/download', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); const { id } = z.strictObject({ id: z.string().max(60) }).parse(body(request)); if(mediaDownloads.busy||aux.download?.state==='downloading')throw Error('Pause o download visual antes de iniciar outro.');return library.download(id); }));
  app.post('/v1/model-library/cancel', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); const { id } = z.strictObject({ id: z.string().max(60) }).parse(body(request)); return library.cancel(id); }));
  app.post('/v1/model-library/install', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); const { id } = z.strictObject({ id: z.string().max(60) }).parse(body(request)); return library.install(id); }));
  app.post('/v1/model-library/load', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); const { key,context } = z.strictObject({ key: z.string().min(1).max(512),context:z.number().int().min(2048).max(131072).default(16384) }).parse(body(request)); if ((await core.snapshot()).tasks.some(task => task.state === 'running')) throw new Error('Aguarde a entrega atual terminar antes de carregar outro modelo'); if (chats.busy||gateway.busy||aux.busy) throw new Error('Pare a resposta atual antes de preparar outra IA.'); if(gateway.status().enabled&&runtime.owns(key)&&runtime.owns(gateway.status().local_model)&&gateway.status().local_model!==key)throw new Error('Desligue Minha API antes de trocar a IA do motor integrado.'); return library.load(key,context); }));
  app.post('/v1/model-library/unload', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); const { instance } = z.strictObject({ instance: z.string().min(1).max(512) }).parse(body(request)); if ((await core.snapshot()).tasks.some(task => task.state === 'running' && task.model === instance)) throw new Error('Este modelo está trabalhando em uma entrega. Pause a entrega primeiro.'); if (chats.busy||gateway.busy||aux.busy) throw new Error('Pare a resposta atual antes de liberar memória.'); if(gateway.status().enabled&&gateway.status().local_model===instance)throw new Error('Desligue Minha API antes de liberar o modelo compartilhado.'); return library.unload(instance); }));
  app.post('/v1/tasks', async request => core.create(body(request), key(request)));
  app.post('/v1/tasks/:id/start', async request => exclusive(async () => { if (core.vault.locked) throw new Error('Cofre bloqueado'); if (chats.busy||gateway.busy||aux.busy) throw new Error('Pare a resposta atual antes de iniciar uma entrega.'); return core.start(id(request), key(request)); }));
  app.post('/v1/tasks/:id/pause', async request => { await core.pause(id(request)); return { ok: true }; });
  app.post('/v1/tasks/:id/cancel', async request => { await core.pause(id(request), true); return { ok: true }; });
  app.post('/v1/tasks/:id/edit', async request => { const data = z.strictObject({ body: z.string().max(262144), expected_hash: z.string().length(64) }).parse(body(request)); return core.edit(id(request), data.body, data.expected_hash, key(request)); });
  app.post('/v1/tasks/:id/restore', async request => { const data = z.strictObject({ version_id: z.string().uuid(), expected_hash: z.string().length(64) }).parse(body(request)); return core.restore(id(request), data.version_id, data.expected_hash, key(request)); });
  app.post('/v1/tasks/:id/review', async request => { const data = z.strictObject({ expected_hash: z.string().length(64), checks: z.array(z.string()).max(10) }).parse(body(request)); return core.review(id(request), data.expected_hash, data.checks, key(request)); });
  app.get('/v1/tasks/:id/download', async (request, reply) => { const state = await core.snapshot(), task = state.tasks.find(t => t.id === id(request)); const version = task?.versions.at(-1); if (!version) throw new Error('Entrega sem arquivo'); return reply.header('Content-Disposition', `attachment; filename="conteudo-${task!.id}.md"`).type('text/markdown; charset=utf-8').send(version.body); });
  app.post('/v1/agents/agent/revoke', async () => { await core.revokeAgent(); return { ok: true }; });
  app.post('/v1/workflows', async request => { const { source } = z.strictObject({ source: z.string().max(32768) }).parse(body(request)); return core.registerWorkflow(source); });
  app.get('/v1/log', async request => { const { from } = z.object({ from: z.coerce.number().int().min(0).default(0) }).parse(request.query); return (await core.store.entries()).filter(entry => entry.seq > from); });
  app.get('/v1/log/export', async (_request, reply) => reply.header('Content-Disposition','attachment; filename="colmeia-auditoria.json"').send(await core.export()));
  app.post('/v1/log/verify', async request => { const data = z.strictObject({ bundle: z.unknown(), trusted_fingerprint: z.string().regex(/^[0-9a-f]{64}$/) }).parse(body(request)); return verifyPackage(data.bundle, data.trusted_fingerprint); });
  app.get('/v1/vault/backup', async (_request, reply) => reply.header('Content-Disposition','attachment; filename="colmeia-cofre-cifrado.json"').type('application/json').send(readFileSync(core.vault.path)));
  app.post('/v1/lock', async () => {await editor.close();await music.stop();await computerControl.stop();await connections.close();await experienceJobs.stop();await mediaDownloads.pause();await pro.pause();await proMedia.close();await aux.close();return exclusive(async () => {
    await aux.close(); await gateway.stop(); await chats.close(); await library.stop();
    for (const task of (await core.snapshot()).tasks.filter(t => t.state === 'running')) await core.pause(task.id);
    await Promise.allSettled([...core.jobs.values()].map(j => j.promise)); core.vault.lock(); return { ok: true };
  });});
  return { app, token, subscription };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = process.cwd();
  const directory = resolve(process.env.COLMEIA_DATA_DIR || join(root, '.data'));
  const port = Number(process.env.COLMEIA_PORT || 4317);
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  const releaseLock = acquireProcessLock(directory);
  const core = new Core(directory, root); await core.init();
  const origin = `http://127.0.0.1:${port}`;
  const { app, token } = await createApp(core, undefined, origin);
  await app.listen({ host: '127.0.0.1', port });
  writeFileSync(join(directory,'session.json'), JSON.stringify({ url: `${origin}/#session=${token}`, port, started_at: Date.now() }), { mode: 0o600 });
  console.log(`LocalNeuron local: ${origin} — sessão no iniciador scripts/open.mjs`);
  const close = async () => { await app.close(); await core.close(); releaseLock(); process.exit(0); };
  process.on('exit', releaseLock);
  process.on('SIGINT', close); process.on('SIGTERM', close);
}
