import type { GenerationOptions, Generation } from './inference.js';
export type Identity = { id: string; name: string; kind: 'human' | 'agent' | 'service'; public_key: string; owner_id: string | null; revoked_seq: number | null; epoch: number };
export type Grant = { body: { human_id: string; agent_id: string; log_id: string; task_id: string; action_hash: string; epoch: number; issued_at: number; expires_at: number }; signature: string };
export type Action = { tool: string; task_id: string; input_hash: string; destination: 'local'; cost_minor: number };
export type Entry = { seq: number; log_id: string; prev_hash: string; at: number; type: string; author_id: string; payload_hash: string; payload_ref: string; action_hash: string | null; authorization: Grant | null; entry_hash: string; author_signature: string };
export type Workflow = { id: string; version: number; title: string; policy: 'local'; budget_minor: number; allowed_tools: string[]; required_checks: string[]; steps: { tool: string }[]; source_hash: string };
export type Version = { id: string; hash: string; previous_hash: string | null; body: string; at: number };
export type Task = { id: string; title: string; brief: string; requirements: string[]; duration_seconds: number; workflow: Workflow; state: 'draft' | 'running' | 'review' | 'validated' | 'paused' | 'cancelled'; mode: 'template' | 'model'; model: string; budget_minor: number; spent_minor: number; reserved_minor: number; action: Action; grants: Record<string, Grant>; versions: Version[]; checks: { name: string; pass: boolean; detail: string }[]; notes: string[]; at: number; error: string | null; generation: number; checkpoint_id: string | null };
export type State = { seal?: string; experience?: import("./experience.js").ExperienceState; chats?: Chat[]; log_id: string; identities: Identity[]; agent: { id: string; scope: string[]; cap_minor: number; epoch: number }; workflows: Workflow[]; tasks: Task[]; reservations: { id: string; task_id: string; amount: number; actual: number | null; state: 'reserved' | 'settled' | 'released' }[]; idempotency: Record<string, { hash: string; result: unknown }> };

export type ChatMessage = { attachments?: import('./chat-context.js').ChatAttachment[]; sources?: import('./chat-context.js').ChatSource[]; id: string; role: "user" | "assistant"; content: string; at: number; status: "pending" | "complete" | "stopped" | "error"; model?: string; options_json?: string; access_json?:string;activities?:import('./agent-tools.js').Activity[]; stats?: Omit<Generation,'text'>; versions?: ChatMessage[]; error?: string };
export type Chat = { bot_id?: string; preferred_model?: string; memory?: string; forked_from?: string; id: string; title: string; at: number; messages: ChatMessage[] };
